const customerSalesDataTableHead={
  "SD_DOC": "Sales Distributon Doc No",
  "ITM_NUMBER": "Item Number of SD Doc",
  "MATERIAL": "Material No",
  "SHORT_TEXT": "Short Text",
  "DOC_TYPE": "Doc type",
  "DOC_DATE": "Document Date",
  "REQ_QTY": "Required Quantity",
  "REQ_DATE": "Required Date",
  "PURCH_NO": "Purchase No",
  "BATCH": "Batch",
  "VALID_FROM": "Valid From",
  "VALID_TO": "Valid To",
  "BILL_BLOCK": "Bill Block",
  "DLV_BLOCK": "Delivery Block",
  "SOLD_TO": "Sold To",
  "NAME": "Name",
  "EXCHG_RATE": "Exchange Rate",
  "DLV_QTY": "Delivered Quantity",
  "BASE_UOM": "Base Unit Of Measure",
  "NET_PRICE": "Net Price",
  "COND_P_UNT": "Conditional Pricing Unit",
  "COND_UNIT": "Condition Unit",
  "NET_VAL_HD": "Net Value of Sales order",
  "NET_VALUE": "Net Value in Document Currency",
  "DIVISION": "Division",
  "DOC_STATUS": "Document Status",
  "SALES_GRP": "Sales Group",
  "SALES_OFF": "Sales Office",
  "SALES_ORG": "Sales Organisation",
  "SALES_UNIT": "SAles Unit",
  "SHIP_POINT": "Shipping point",
  "DISTR_CHAN": "Distribution Channel",
  "GI_DATE": "Goods Issue Date",
  "CURRENCY": "SD Document Currency",
  "PLANT": "Plant",
  "STORE_LOC": "Storage Location",
  "ORD_REASON": "Order Reason",
  "REASON_REJ": "Reason for Rejection",
  "B_UOM_ISO": "Base unit of measure in ISO code",
  "CD_UNT_ISO": "Condition unit of measure in UoM",
  "S_UNIT_ISO": "Sales unit in ISO code",
  "CURR_ISO": "ISO Currency Code",
  "PURCH_NO_C": "Customer Purchase No",
  "EXCHG_RATE_V": "Indirectly quoted exchange rate for pricing and statistics",
  "MAT_EXT": "Long Material Number",
  "MAT_GUID": "External GUID for MATERIAL Field",
  "MAT_VERS": "Version Number for MATERIAL Field",
  "CREATION_DATE": "Created Date",
  "CREATION_TIME": "Created Time",
  "STATUS_DOC": "Status Document",
  "REQ_SEGMENT": "Requirement Segment",
  "MATERIAL_LONG": "Material Number Long"
}

export default customerSalesDataTableHead;