const axios = require("axios");
const express = require("express");
const router = express.Router();

const config = {
  auth: {
    username: "POUSER@1",
    password: "Tech@2022",
  },
  headers: { "Content-Type": "text/xml" },
};

//@type      POST
//@route     /login
//@desc      route to authenticate login
//@access    PUBLIC
router.post("/login", (req, res) => {
  const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_login`;
  const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
  <ns0:ZFM_CUSTOMER_LOGIN_EYUWANKG xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
  <PASSWORD>EYUWANKG123</PASSWORD>
  <USERNAME>CUSTOMER@A1</USERNAME>
  </ns0:ZFM_CUSTOMER_LOGIN_EYUWANKG>`;
  axios
    .post(requestURL, bodyRequest, config)
    .then(function (response) {
      console.log("response", response);
      res.send(response.data);
    })
    .catch(function (error) {
      console.log(error);
    });
});

//@type      POST
//@route     /customerprofile
//@desc      route to get customerprofile data
//@access    PUBLIC
router.post("/customerprofile", (req, res) => {
   const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_profile`;
   const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
   <ns0:ZFM_CUST_PROFILE_EYUWANKG xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
      <CUSTOMER_ID>${req.body.customer_id}</CUSTOMER_ID>
      <CUSTOMERBANKDETAIL>
         <item>
            <CUSTOMER/>
            <BANK_CTRY/>
            <BANK_KEY/>
            <BANK_ACCT/>
            <CTRL_KEY/>
            <PARTNER_BK/>
            <COLL_AUTH/>
            <BANK_REF/>
         </item>
      </CUSTOMERBANKDETAIL>
      <CUSTOMERIBANDETAIL>
         <item>
            <CUSTOMER/>
            <BANK_CTRY/>
            <BANK_KEY/>
            <BANK_ACCT/>
            <CTRL_KEY/>
            <IBAN/>
            <VALID_FROM/>
            <DUMMY/>
         </item>
      </CUSTOMERIBANDETAIL>
      <CUSTOMERSEPADETAIL>
         <item>
            <CUSTOMER/>
            <IBAN/>
            <APPLICATION/>
            <SEPA_CREDITOR_ID/>
            <SEPA_MANDATE_ID/>
            <DUMMY/>
         </item>
      </CUSTOMERSEPADETAIL>
   </ns0:ZFM_CUST_PROFILE_EYUWANKG>`;

  axios
    .post(requestURL, bodyRequest, config)
    .then(function (response) {
      res.send({data:response.data});
    })
    .catch(function (error) {
      console.log(error);
    });
});

// INQUIRY DATA

//@type      POST
//@route     /inquiryList
//@desc      route to get inquiryList data
//@access    PUBLIC
router.post("/inquiryList", (req, res) => {
  const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_inquiry_list`;
  const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
  <ns0:ZFM_CUST_INQUIRY_LIST_SD xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
  <CUSTOMER_ID>${req.body.customer_id}</CUSTOMER_ID>
     <IT_INQUIRY_LIST>
        <item>
           <MANDT/>
           <VBELN/>
           <ERDAT/>
           <ERZET/>
           <ERNAM/>
           <ANGDT/>
           <BNDDT/>
           <AUDAT/>
           <VBTYP/>
           <TRVOG/>
           <AUART/>
           <AUGRU/>
           <GWLDT/>
           <SUBMI/>
           <LIFSK/>
           <FAKSK/>
           <NETWR/>
           <WAERK/>
           <VKORG/>
           <VTWEG/>
           <SPART/>
           <VKGRP/>
           <VKBUR/>
           <GSBER/>
           <GSKST/>
           <GUEBG/>
           <GUEEN/>
           <KNUMV/>
           <VDATU/>
           <VPRGR/>
           <AUTLF/>
           <VBKLA/>
           <VBKLT/>
           <KALSM/>
           <VSBED/>
           <FKARA/>
           <AWAHR/>
           <KTEXT/>
           <BSTNK/>
           <BSARK/>
           <BSTDK/>
           <BSTZD/>
           <IHREZ/>
           <BNAME/>
           <TELF1/>
           <MAHZA/>
           <MAHDT/>
           <KUNNR/>
           <KOSTL/>
           <STAFO/>
           <STWAE/>
           <AEDAT/>
           <KVGR1/>
           <KVGR2/>
           <KVGR3/>
           <KVGR4/>
           <KVGR5/>
           <KNUMA/>
           <KOKRS/>
           <PS_PSP_PNR/>
           <KURST/>
           <KKBER/>
           <KNKLI/>
           <GRUPP/>
           <SBGRP/>
           <CTLPC/>
           <CMWAE/>
           <CMFRE/>
           <CMNUP/>
           <CMNGV/>
           <AMTBL/>
           <HITYP_PR/>
           <ABRVW/>
           <ABDIS/>
           <VGBEL/>
           <OBJNR/>
           <BUKRS_VF/>
           <TAXK1/>
           <TAXK2/>
           <TAXK3/>
           <TAXK4/>
           <TAXK5/>
           <TAXK6/>
           <TAXK7/>
           <TAXK8/>
           <TAXK9/>
           <XBLNR/>
           <ZUONR/>
           <VGTYP/>
           <KALSM_CH/>
           <AGRZR/>
           <AUFNR/>
           <QMNUM/>
           <VBELN_GRP/>
           <SCHEME_GRP/>
           <ABRUF_PART/>
           <ABHOD/>
           <ABHOV/>
           <ABHOB/>
           <RPLNR/>
           <VZEIT/>
           <STCEG_L/>
           <LANDTX/>
           <XEGDR/>
           <ENQUEUE_GRP/>
           <DAT_FZAU/>
           <FMBDAT/>
           <VSNMR_V/>
           <HANDLE/>
           <PROLI/>
           <CONT_DG/>
           <CRM_GUID/>
           <UPD_TMSTMP/>
           <MSR_ID/>
           <TM_CTRL_KEY/>
           <HANDOVERLOC/>
           <_DATAAGING/>
           <PSM_BUDAT/>
           <FSH_KVGR6/>
           <FSH_KVGR7/>
           <FSH_KVGR8/>
           <FSH_KVGR9/>
           <FSH_KVGR10/>
           <FSH_REREG/>
           <FSH_CQ_CHECK/>
           <FSH_VRSN_STATUS/>
           <FSH_TRANSACTION/>
           <FSH_VAS_CG/>
           <FSH_CANDATE/>
           <FSH_SS/>
           <FSH_OS_STG_CHANGE/>
           <SWENR/>
           <SMENR/>
           <PHASE/>
           <MTLAUR/>
           <STAGE/>
           <HB_CONT_REASON/>
           <HB_EXPDATE/>
           <HB_RESDATE/>
           <MILL_APPL_ID/>
           <TAS/>
           <BETC/>
           <MOD_ALLOW/>
           <CANCEL_ALLOW/>
           <PAY_METHOD/>
           <BPN/>
           <REP_FREQ/>
           <LOGSYSB/>
           <KALCD/>
           <MULTI/>
           <SPPAYM/>
           <WTYSC_CLM_HDR/>
        </item>
     </IT_INQUIRY_LIST>
  </ns0:ZFM_CUST_INQUIRY_LIST_SD>`;

  axios
    .post(requestURL, bodyRequest, config)
    .then(function (response) {
      res.send({data:response.data});
    })
    .catch(function (error) {
      console.log(error);
    });
});

//@type      POST
//@route     /inquirydetail
//@desc      route to get inquirydetail data
//@access    PUBLIC
router.post("/inquirydetail", (req, res) => {
   const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_inquiry_detail`;
   //90000000
   const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
   <ns0:ZFM_CUST_INQUIRY_DETAILS_SD xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
      <INQUIRY_NO>${req.body.inquiry_no}</INQUIRY_NO>
      <IT_INQUIRY_DETAILS>
         <item>
            <MANDT/>
            <VBELN/>
            <POSNR/>
            <MATNR/>
            <MATWA/>
            <PMATN/>
            <CHARG/>
            <MATKL/>
            <ARKTX/>
            <PSTYV/>
            <POSAR/>
            <LFREL/>
            <FKREL/>
            <UEPOS/>
            <GRPOS/>
            <ABGRU/>
            <PRODH/>
            <ZWERT/>
            <ZMENG/>
            <ZIEME/>
            <UMZIZ/>
            <UMZIN/>
            <MEINS/>
            <SMENG/>
            <ABLFZ/>
            <ABDAT/>
            <ABSFZ/>
            <POSEX/>
            <KDMAT/>
            <KBVER/>
            <KEVER/>
            <VKGRU/>
            <VKAUS/>
            <GRKOR/>
            <FMENG/>
            <UEBTK/>
            <UEBTO/>
            <UNTTO/>
            <FAKSP/>
            <ATPKZ/>
            <RKFKF/>
            <SPART/>
            <GSBER/>
            <NETWR/>
            <WAERK/>
            <ANTLF/>
            <KZTLF/>
            <CHSPL/>
            <KWMENG/>
            <LSMENG/>
            <KBMENG/>
            <KLMENG/>
            <VRKME/>
            <UMVKZ/>
            <UMVKN/>
            <BRGEW/>
            <NTGEW/>
            <GEWEI/>
            <VOLUM/>
            <VOLEH/>
            <VBELV/>
            <POSNV/>
            <VGBEL/>
            <VGPOS/>
            <VOREF/>
            <UPFLU/>
            <ERLRE/>
            <LPRIO/>
            <WERKS/>
            <LGORT/>
            <VSTEL/>
            <ROUTE/>
            <STKEY/>
            <STDAT/>
            <STLNR/>
            <STPOS/>
            <AWAHR/>
            <ERDAT/>
            <ERNAM/>
            <ERZET/>
            <TAXM1/>
            <TAXM2/>
            <TAXM3/>
            <TAXM4/>
            <TAXM5/>
            <TAXM6/>
            <TAXM7/>
            <TAXM8/>
            <TAXM9/>
            <VBEAF/>
            <VBEAV/>
            <VGREF/>
            <NETPR/>
            <KPEIN/>
            <KMEIN/>
            <SHKZG/>
            <SKTOF/>
            <MTVFP/>
            <SUMBD/>
            <KONDM/>
            <KTGRM/>
            <BONUS/>
            <PROVG/>
            <EANNR/>
            <PRSOK/>
            <BWTAR/>
            <BWTEX/>
            <XCHPF/>
            <XCHAR/>
            <LFMNG/>
            <STAFO/>
            <WAVWR/>
            <KZWI1/>
            <KZWI2/>
            <KZWI3/>
            <KZWI4/>
            <KZWI5/>
            <KZWI6/>
            <STCUR/>
            <AEDAT/>
            <EAN11/>
            <FIXMG/>
            <PRCTR/>
            <MVGR1/>
            <MVGR2/>
            <MVGR3/>
            <MVGR4/>
            <MVGR5/>
            <KMPMG/>
            <SUGRD/>
            <SOBKZ/>
            <VPZUO/>
            <PAOBJNR/>
            <PS_PSP_PNR/>
            <AUFNR/>
            <VPMAT/>
            <VPWRK/>
            <PRBME/>
            <UMREF/>
            <KNTTP/>
            <KZVBR/>
            <SERNR/>
            <OBJNR/>
            <ABGRS/>
            <BEDAE/>
            <CMPRE/>
            <CMTFG/>
            <CMPNT/>
            <CMKUA/>
            <CUOBJ/>
            <CUOBJ_CH/>
            <CEPOK/>
            <KOUPD/>
            <SERAIL/>
            <ANZSN/>
            <NACHL/>
            <MAGRV/>
            <MPROK/>
            <VGTYP/>
            <PROSA/>
            <UEPVW/>
            <KALNR/>
            <KLVAR/>
            <SPOSN/>
            <KOWRR/>
            <STADAT/>
            <EXART/>
            <PREFE/>
            <KNUMH/>
            <CLINT/>
            <CHMVS/>
            <STLTY/>
            <STLKN/>
            <STPOZ/>
            <STMAN/>
            <ZSCHL_K/>
            <KALSM_K/>
            <KALVAR/>
            <KOSCH/>
            <UPMAT/>
            <UKONM/>
            <MFRGR/>
            <PLAVO/>
            <KANNR/>
            <CMPRE_FLT/>
            <ABFOR/>
            <ABGES/>
            <J_1BCFOP/>
            <J_1BTAXLW1/>
            <J_1BTAXLW2/>
            <J_1BTXSDC/>
            <WKTNR/>
            <WKTPS/>
            <SKOPF/>
            <KZBWS/>
            <WGRU1/>
            <WGRU2/>
            <KNUMA_PI/>
            <KNUMA_AG/>
            <KZFME/>
            <LSTANR/>
            <TECHS/>
            <MWSBP/>
            <BERID/>
            <PCTRF/>
            <LOGSYS_EXT/>
            <J_1BTAXLW3/>
            <J_1BTAXLW4/>
            <J_1BTAXLW5/>
            <STOCKLOC/>
            <SLOCTYPE/>
            <MSR_RET_REASON/>
            <MSR_REFUND_CODE/>
            <MSR_APPROV_BLOCK/>
            <NRAB_KNUMH/>
            <TRMRISK_RELEVANT/>
            <SGT_RCAT/>
            <HANDOVERLOC/>
            <HANDOVERDATE/>
            <HANDOVERTIME/>
            <TC_AUT_DET/>
            <MANUAL_TC_REASON/>
            <FISCAL_INCENTIVE/>
            <TAX_SUBJECT_ST/>
            <FISCAL_INCENTIVE_ID/>
            <SPCSTO/>
            <_DATAAGING/>
            <REVACC_REFID/>
            <REVACC_REFTYPE/>
            <_-BEV1_-SRFUND/>
            <AUFPL_OLC/>
            <APLZL_OLC/>
            <FERC_IND/>
            <FSH_SEASON_YEAR/>
            <FSH_SEASON/>
            <FSH_COLLECTION/>
            <FSH_THEME/>
            <FSH_CRSD/>
            <FSH_SEAREF/>
            <FSH_CANDATE/>
            <FSH_PSM_PFM_SPLIT/>
            <FSH_VAS_REL/>
            <FSH_VAS_PRNT_ID/>
            <FSH_TRANSACTION/>
            <FSH_ITEM_GROUP/>
            <FSH_ITEM/>
            <FSH_VASREF/>
            <FSH_GRID_COND_REC/>
            <KOSTL/>
            <FONDS/>
            <FISTL/>
            <FKBER/>
            <GRANT_NBR/>
            <BUDGET_PD/>
            <IUID_RELEVANT/>
            <MILL_SE_GPOSN/>
            <PRS_OBJNR/>
            <PRS_SD_SPSNR/>
            <PRS_WORK_PERIOD/>
            <TAS/>
            <BETC/>
            <MOD_ALLOW/>
            <CANCEL_ALLOW/>
            <PAY_METHOD/>
            <BPN/>
            <REP_FREQ/>
            <FMFGUS_KEY/>
            <PARGB/>
            <AUFPL_OAA/>
            <APLZL_OAA/>
            <WRF_CHARSTC1/>
            <WRF_CHARSTC2/>
            <WRF_CHARSTC3/>
            <ARSNUM/>
            <ARSPOS/>
            <WTYSC_CLMITEM/>
         </item>
      </IT_INQUIRY_DETAILS>
   </ns0:ZFM_CUST_INQUIRY_DETAILS_SD>`;

  axios
    .post(requestURL, bodyRequest, config)
    .then(function (response) {
      res.send({data:response.data});
    })
    .catch(function (error) {
      console.log(error);
    });
});

// SALES DATA

//@type      POST
//@route     /saleorderlist
//@desc      route to get saleorderlist data
//@access    PUBLIC
router.post("/saleorderlist", (req, res) => {
  const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_sales_list`;
  const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
  <ns0:ZFM_CUST_SALES_ORDER_DATA xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
  <CUSTOMER_NO>${req.body.customer_id}</CUSTOMER_NO>
     <IT_SALES_ORDER>
        <item>
        <SD_DOC/>
         <ITM_NUMBER/>
         <MATERIAL/>
         <SHORT_TEXT/>
         <DOC_TYPE/>
         <DOC_DATE/>
         <REQ_QTY/>
         <REQ_DATE/>
         <PURCH_NO/>
         <BATCH/>
         <VALID_FROM/>
         <VALID_TO/>
         <BILL_BLOCK/>
         <DLV_BLOCK/>
         <SOLD_TO/>
         <NAME/>
         <EXCHG_RATE/>
         <DLV_QTY/>
         <BASE_UOM/>
         <NET_PRICE/>
         <COND_P_UNT/>
         <COND_UNIT/>
         <NET_VAL_HD/>
         <NET_VALUE/>
         <DIVISION/>
         <DOC_STATUS/>
         <SALES_GRP/>
         <SALES_OFF/>
         <SALES_ORG/>
         <SALES_UNIT/>
         <SHIP_POINT/>
         <DISTR_CHAN/>
         <GI_DATE/>
         <CURRENCY/>
         <PLANT/>
         <STORE_LOC/>
         <ORD_REASON/>
         <REASON_REJ/>
         <B_UOM_ISO/>
         <CD_UNT_ISO/>
         <S_UNIT_ISO/>
         <CURR_ISO/>
         <PURCH_NO_C/>
         <EXCHG_RATE_V/>
         <MAT_EXT/>
         <MAT_GUID/>
         <MAT_VERS/>
         <CREATION_DATE/>
         <CREATION_TIME/>
         <STATUS_DOC/>
         <REQ_SEGMENT/>
         <MATERIAL_LONG/>
        </item>
     </IT_SALES_ORDER>
  </ns0:ZFM_CUST_SALES_ORDER_DATA>`;

  axios
    .post(requestURL, bodyRequest, config)
    .then(function (response) {
      res.send({data:response.data});
    })
    .catch(function (error) {
      console.log(error);
    });
});

//@type      POST
//@route     /salestatus
//@desc      route to get salestatus data
//@access    PUBLIC
router.post("/salestatus", (req, res) => {
   const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_sales_status`;
   const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
   <ns0:ZFM_CUST_SALES_STATUS xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
      <SALES_DOC_NO>${req.body.sales_doc_no}</SALES_DOC_NO>
      <ET_RESULT>
         <item>
            <DOC_NUMBER/>
            <DOC_DATE/>
            <PURCH_NO/>
            <PRC_STAT_H/>
            <DLV_STAT_H/>
            <REQ_DATE_H/>
            <DLV_BLOCK/>
            <ITM_NUMBER/>
            <MATERIAL/>
            <SHORT_TEXT/>
            <REQ_DATE/>
            <REQ_QTY/>
            <CUM_CF_QTY/>
            <SALES_UNIT/>
            <NET_VALUE/>
            <CURRENCY/>
            <NET_PRICE/>
            <COND_P_UNT/>
            <COND_UNIT/>
            <DLV_STAT_I/>
            <DELIV_NUMB/>
            <DELIV_ITEM/>
            <DELIV_DATE/>
            <DLV_QTY/>
            <REF_QTY/>
            <S_UNIT_ISO/>
            <CD_UNT_ISO/>
            <CURR_ISO/>
            <MATERIAL_EXTERNAL/>
            <MATERIAL_GUID/>
            <MATERIAL_VERSION/>
            <PO_ITM_NO/>
            <CREATION_DATE/>
            <CREATION_TIME/>
            <S_UNIT_DLV/>
            <DLV_UNIT_ISO/>
            <REA_FOR_RE/>
            <PURCH_NO_C/>
            <MATERIAL_LONG/>
         </item>
      </ET_RESULT>
   </ns0:ZFM_CUST_SALES_STATUS>`;

  axios
    .post(requestURL, bodyRequest, config)
    .then(function (response) {
      res.send({data:response.data});
    })
    .catch(function (error) {
      console.log(error);
    });
});

// INVOICE DATA

//@type      POST
//@route     /invoicelist
//@desc      route to get invoicelist data
//@access    PUBLIC
router.post("/invoicelist", (req, res) => {
   const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_invoice_list`;
   const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
  <ns0:ZFM_CUSTOMER_INVOICE_LIST xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
  <CUSTOMER_NO>${req.body.customer_id}</CUSTOMER_NO>
     <IT_INVOICE_LIST>
        <item>
           <MANDT/>
           <VBELN/>
           <FKART/>
           <FKTYP/>
           <VBTYP/>
           <WAERK/>
           <VKORG/>
           <VTWEG/>
           <KALSM/>
           <KNUMV/>
           <VSBED/>
           <FKDAT/>
           <BELNR/>
           <GJAHR/>
           <POPER/>
           <KONDA/>
           <KDGRP/>
           <BZIRK/>
           <PLTYP/>
           <INCO1/>
           <INCO2/>
           <EXPKZ/>
           <RFBSK/>
           <MRNKZ/>
           <KURRF/>
           <CPKUR/>
           <VALTG/>
           <VALDT/>
           <ZTERM/>
           <ZLSCH/>
           <KTGRD/>
           <LAND1/>
           <REGIO/>
           <COUNC/>
           <CITYC/>
           <BUKRS/>
           <TAXK1/>
           <TAXK2/>
           <TAXK3/>
           <TAXK4/>
           <TAXK5/>
           <TAXK6/>
           <TAXK7/>
           <TAXK8/>
           <TAXK9/>
           <NETWR/>
           <ZUKRI/>
           <ERNAM/>
           <ERZET/>
           <ERDAT/>
           <STAFO/>
           <KUNRG/>
           <KUNAG/>
           <MABER/>
           <STWAE/>
           <EXNUM/>
           <STCEG/>
           <AEDAT/>
           <SFAKN/>
           <KNUMA/>
           <FKART_RL/>
           <FKDAT_RL/>
           <KURST/>
           <MSCHL/>
           <MANSP/>
           <SPART/>
           <KKBER/>
           <KNKLI/>
           <CMWAE/>
           <CMKUF/>
           <HITYP_PR/>
           <BSTNK_VF/>
           <VBUND/>
           <FKART_AB/>
           <KAPPL/>
           <LANDTX/>
           <STCEG_H/>
           <STCEG_L/>
           <XBLNR/>
           <ZUONR/>
           <MWSBK/>
           <LOGSYS/>
           <FKSTO/>
           <XEGDR/>
           <RPLNR/>
           <LCNUM/>
           <J_1AFITP/>
           <KURRF_DAT/>
           <AKWAE/>
           <AKKUR/>
           <KIDNO/>
           <BVTYP/>
           <NUMPG/>
           <BUPLA/>
           <VKONT/>
           <FKK_DOCSTAT/>
           <NRZAS/>
           <SPE_BILLING_IND/>
           <VTREF/>
           <FK_SOURCE_SYS/>
           <FKTYP_CRM/>
           <STGRD/>
           <VBTYP_EXT/>
           <J_1TPBUPL/>
           <INCOV/>
           <INCO2_L/>
           <INCO3_L/>
           <DPC_REL/>
           <MNDID/>
           <PAY_TYPE/>
           <SEPON/>
           <MNDVG/>
           <SPPAYM/>
           <SPPORD/>
        </item>
     </IT_INVOICE_LIST>
  </ns0:ZFM_CUSTOMER_INVOICE_LIST>`;
 
   axios
     .post(requestURL, bodyRequest, config)
     .then(function (response) {
      res.send({data:response.data});
     })
     .catch(function (error) {
       console.log(error);
     });
 });

//@type      POST
//@route     /invoicedetail
//@desc      route to get invoicedetail data
//@access    PUBLIC
router.post("/invoicedetail", (req, res) => {
   const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_invoice_detail`;  
   //90000000
   const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
  <ns0:ZFM_CUST_INVOICE_DETAIL xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
     <INVOICE_NO>${req.body.invoice_no}</INVOICE_NO>
     <IT_INVOICE_DATA>
        <item>
           <MANDT/>
           <VBELN/>
           <POSNR/>
           <UEPOS/>
           <FKIMG/>
           <VRKME/>
           <UMVKZ/>
           <UMVKN/>
           <MEINS/>
           <SMENG/>
           <FKLMG/>
           <LMENG/>
           <NTGEW/>
           <BRGEW/>
           <GEWEI/>
           <VOLUM/>
           <VOLEH/>
           <GSBER/>
           <PRSDT/>
           <FBUDA/>
           <KURSK/>
           <NETWR/>
           <VBELV/>
           <POSNV/>
           <VGBEL/>
           <VGPOS/>
           <VGTYP/>
           <AUBEL/>
           <AUPOS/>
           <AUREF/>
           <MATNR/>
           <ARKTX/>
           <PMATN/>
           <CHARG/>
           <MATKL/>
           <PSTYV/>
           <POSAR/>
           <PRODH/>
           <VSTEL/>
           <ATPKZ/>
           <SPART/>
           <POSPA/>
           <WERKS/>
           <ALAND/>
           <WKREG/>
           <WKCOU/>
           <WKCTY/>
           <TAXM1/>
           <TAXM2/>
           <TAXM3/>
           <TAXM4/>
           <TAXM5/>
           <TAXM6/>
           <TAXM7/>
           <TAXM8/>
           <TAXM9/>
           <KOWRR/>
           <PRSFD/>
           <SKTOF/>
           <SKFBP/>
           <KONDM/>
           <KTGRM/>
           <KOSTL/>
           <BONUS/>
           <PROVG/>
           <EANNR/>
           <VKGRP/>
           <VKBUR/>
           <SPARA/>
           <SHKZG/>
           <ERNAM/>
           <ERDAT/>
           <ERZET/>
           <BWTAR/>
           <LGORT/>
           <STAFO/>
           <WAVWR/>
           <KZWI1/>
           <KZWI2/>
           <KZWI3/>
           <KZWI4/>
           <KZWI5/>
           <KZWI6/>
           <STCUR/>
           <UVPRS/>
           <UVALL/>
           <EAN11/>
           <PRCTR/>
           <KVGR1/>
           <KVGR2/>
           <KVGR3/>
           <KVGR4/>
           <KVGR5/>
           <MVGR1/>
           <MVGR2/>
           <MVGR3/>
           <MVGR4/>
           <MVGR5/>
           <MATWA/>
           <BONBA/>
           <KOKRS/>
           <PAOBJNR/>
           <PS_PSP_PNR/>
           <AUFNR/>
           <TXJCD/>
           <CMPRE/>
           <CMPNT/>
           <CUOBJ/>
           <CUOBJ_CH/>
           <KOUPD/>
           <UECHA/>
           <XCHAR/>
           <ABRVW/>
           <SERNR/>
           <BZIRK_AUFT/>
           <KDGRP_AUFT/>
           <KONDA_AUFT/>
           <LLAND_AUFT/>
           <MPROK/>
           <PLTYP_AUFT/>
           <REGIO_AUFT/>
           <VKORG_AUFT/>
           <VTWEG_AUFT/>
           <ABRBG/>
           <PROSA/>
           <UEPVW/>
           <AUTYP/>
           <STADAT/>
           <FPLNR/>
           <FPLTR/>
           <AKTNR/>
           <KNUMA_PI/>
           <KNUMA_AG/>
           <PREFE/>
           <MWSBP/>
           <AUGRU_AUFT/>
           <FAREG/>
           <UPMAT/>
           <UKONM/>
           <CMPRE_FLT/>
           <ABFOR/>
           <ABGES/>
           <J_1ARFZ/>
           <J_1AREGIO/>
           <J_1AGICD/>
           <J_1ADTYP/>
           <J_1ATXREL/>
           <J_1BCFOP/>
           <J_1BTAXLW1/>
           <J_1BTAXLW2/>
           <J_1BTXSDC/>
           <BRTWR/>
           <WKTNR/>
           <WKTPS/>
           <RPLNR/>
           <KURSK_DAT/>
           <WGRU1/>
           <WGRU2/>
           <KDKG1/>
           <KDKG2/>
           <KDKG3/>
           <KDKG4/>
           <KDKG5/>
           <VKAUS/>
           <J_1AINDXP/>
           <J_1AIDATEP/>
           <KZFME/>
           <MWSKZ/>
           <VERTT/>
           <VERTN/>
           <SGTXT/>
           <DELCO/>
           <BEMOT/>
           <RRREL/>
           <AKKUR/>
           <WMINR/>
           <VGBEL_EX/>
           <VGPOS_EX/>
           <LOGSYS/>
           <VGTYP_EX/>
           <J_1BTAXLW3/>
           <J_1BTAXLW4/>
           <J_1BTAXLW5/>
           <MSR_ID/>
           <MSR_REFUND_CODE/>
           <MSR_RET_REASON/>
           <NRAB_KNUMH/>
           <NRAB_VALUE/>
           <DISPUTE_CASE/>
           <FUND_USAGE_ITEM/>
           <FARR_RELTYPE/>
           <CLAIMS_TAXATION/>
           <KURRF_DAT_ORIG/>
           <VGTYP_EXT/>
           <SGT_RCAT/>
           <SGT_SCAT/>
           <AUFPL/>
           <APLZL/>
           <DPCNR/>
           <DCPNR/>
           <DPNRB/>
           <PEROP_BEG/>
           <PEROP_END/>
           <FMFGUS_KEY/>
           <FSH_SEASON_YEAR/>
           <FSH_SEASON/>
           <FSH_COLLECTION/>
           <FSH_THEME/>
           <FONDS/>
           <FISTL/>
           <FKBER/>
           <GRANT_NBR/>
           <BUDGET_PD/>
           <PRS_WORK_PERIOD/>
           <PPRCTR/>
           <PARGB/>
           <AUFPL_OAA/>
           <APLZL_OAA/>
           <CAMPAIGN/>
           <COMPREAS/>
           <WRF_CHARSTC1/>
           <WRF_CHARSTC2/>
           <WRF_CHARSTC3/>
        </item>
     </IT_INVOICE_DATA>
  </ns0:ZFM_CUST_INVOICE_DETAIL>`;

  axios
    .post(requestURL, bodyRequest, config)
    .then(function (response) {
      
      res.send({data:response.data});
    })
    .catch(function (error) {
      console.log(error);
    });
});

// DELIVERY DATA

//@type      POST
//@route     /deliverylist
//@desc      route to get deliverylist data
//@access    PUBLIC
router.post("/deliverylist", (req, res) => {
   const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_delivery_list`;
   const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
  <ns0:ZFM_CUSTOMER_DELIVERY_LIST xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
     <CUSTOMER_ID>${req.body.customer_id}</CUSTOMER_ID>
     <RESULT_DELIVERY_HEADER>
        <item>
           <MANDT/>
           <VBELN/>
           <ERNAM/>
           <ERZET/>
           <ERDAT/>
           <BZIRK/>
           <VSTEL/>
           <VKORG/>
           <LFART/>
           <AUTLF/>
           <KZAZU/>
           <WADAT/>
           <LDDAT/>
           <TDDAT/>
           <LFDAT/>
           <KODAT/>
           <ABLAD/>
           <INCO1/>
           <INCO2/>
           <EXPKZ/>
           <ROUTE/>
           <FAKSK/>
           <LIFSK/>
           <VBTYP/>
           <KNFAK/>
           <TPQUA/>
           <TPGRP/>
           <LPRIO/>
           <VSBED/>
           <KUNNR/>
           <KUNAG/>
           <KDGRP/>
           <STZKL/>
           <STZZU/>
           <BTGEW/>
           <NTGEW/>
           <GEWEI/>
           <VOLUM/>
           <VOLEH/>
           <ANZPK/>
           <BEROT/>
           <LFUHR/>
           <GRULG/>
           <LSTEL/>
           <TRAGR/>
           <FKARV/>
           <FKDAT/>
           <PERFK/>
           <ROUTA/>
           <STAFO/>
           <KALSM/>
           <KNUMV/>
           <WAERK/>
           <VKBUR/>
           <VBEAK/>
           <ZUKRL/>
           <VERUR/>
           <COMMN/>
           <STWAE/>
           <STCUR/>
           <EXNUM/>
           <AENAM/>
           <AEDAT/>
           <LGNUM/>
           <LISPL/>
           <VKOIV/>
           <VTWIV/>
           <SPAIV/>
           <FKAIV/>
           <PIOIV/>
           <FKDIV/>
           <KUNIV/>
           <KKBER/>
           <KNKLI/>
           <GRUPP/>
           <SBGRP/>
           <CTLPC/>
           <CMWAE/>
           <AMTBL/>
           <BOLNR/>
           <LIFNR/>
           <TRATY/>
           <TRAID/>
           <CMFRE/>
           <CMNGV/>
           <XABLN/>
           <BLDAT/>
           <WADAT_IST/>
           <TRSPG/>
           <TPSID/>
           <LIFEX/>
           <TERNR/>
           <KALSM_CH/>
           <KLIEF/>
           <KALSP/>
           <KNUMP/>
           <NETWR/>
           <AULWE/>
           <WERKS/>
           <LCNUM/>
           <ABSSC/>
           <KOUHR/>
           <TDUHR/>
           <LDUHR/>
           <WAUHR/>
           <LGTOR/>
           <LGBZO/>
           <AKWAE/>
           <AKKUR/>
           <AKPRZ/>
           <PROLI/>
           <XBLNR/>
           <HANDLE/>
           <TSEGFL/>
           <TSEGTP/>
           <TZONIS/>
           <TZONRC/>
           <CONT_DG/>
           <VERURSYS/>
           <KZWAB/>
           <VLSTK/>
           <TCODE/>
           <VSART/>
           <TRMTYP/>
           <SDABW/>
           <VBUND/>
           <XWOFF/>
           <DIRTA/>
           <PRVBE/>
           <FOLAR/>
           <PODAT/>
           <POTIM/>
           <VGANZ/>
           <IMWRK/>
           <SPE_LOEKZ/>
           <SPE_LOC_SEQ/>
           <SPE_ACC_APP_STS/>
           <SPE_SHP_INF_STS/>
           <SPE_RET_CANC/>
           <SPE_WAUHR_IST/>
           <SPE_WAZONE_IST/>
           <SPE_REV_VLSTK/>
           <SPE_LE_SCENARIO/>
           <SPE_ORIG_SYS/>
           <SPE_CHNG_SYS/>
           <SPE_GEOROUTE/>
           <SPE_GEOROUTEIND/>
           <SPE_CARRIER_IND/>
           <SPE_GTS_REL/>
           <SPE_GTS_RT_CDE/>
           <SPE_REL_TMSTMP/>
           <SPE_UNIT_SYSTEM/>
           <SPE_INV_BFR_GI/>
           <SPE_QI_STATUS/>
           <SPE_RED_IND/>
           <SAKES/>
           <SPE_LIFEX_TYPE/>
           <SPE_TTYPE/>
           <INCOV/>
           <INCO2_L/>
           <INCO3_L/>
           <TRMTYP_LONG/>
           <VBTYP_LONG/>
        </item>
     </RESULT_DELIVERY_HEADER>
     <RESULT_DELIVERY_ITEM>
        <item>
           <MANDT/>
           <VBELN/>
           <POSNR/>
           <PSTYV/>
           <ERNAM/>
           <ERZET/>
           <ERDAT/>
           <MATNR/>
           <MATWA/>
           <MATKL/>
           <WERKS/>
           <LGORT/>
           <CHARG/>
           <LICHN/>
           <KDMAT/>
           <PRODH/>
           <LFIMG/>
           <MEINS/>
           <VRKME/>
           <UMVKZ/>
           <UMVKN/>
           <NTGEW/>
           <BRGEW/>
           <GEWEI/>
           <VOLUM/>
           <VOLEH/>
           <KZTLF/>
           <UEBTK/>
           <UEBTO/>
           <UNTTO/>
           <CHSPL/>
           <FAKSP/>
           <MBDAT/>
           <LGMNG/>
           <ARKTX/>
           <LGPBE/>
           <VBELV/>
           <POSNV/>
           <VBTYV/>
           <VGSYS/>
           <VGBEL/>
           <VGPOS/>
           <UPFLU/>
           <UEPOS/>
           <FKREL/>
           <LADGR/>
           <TRAGR/>
           <KOMKZ/>
           <LGNUM/>
           <LISPL/>
           <LGTYP/>
           <LGPLA/>
           <BWTEX/>
           <BWART/>
           <BWLVS/>
           <KZDLG/>
           <BDART/>
           <PLART/>
           <MTART/>
           <XCHPF/>
           <XCHAR/>
           <VGREF/>
           <POSAR/>
           <BWTAR/>
           <SUMBD/>
           <MTVFP/>
           <EANNR/>
           <GSBER/>
           <VKBUR/>
           <VKGRP/>
           <VTWEG/>
           <SPART/>
           <GRKOR/>
           <FMENG/>
           <ANTLF/>
           <VBEAF/>
           <VBEAV/>
           <STAFO/>
           <WAVWR/>
           <KZWI1/>
           <KZWI2/>
           <KZWI3/>
           <KZWI4/>
           <KZWI5/>
           <KZWI6/>
           <SOBKZ/>
           <AEDAT/>
           <EAN11/>
           <KVGR1/>
           <KVGR2/>
           <KVGR3/>
           <KVGR4/>
           <KVGR5/>
           <MVGR1/>
           <MVGR2/>
           <MVGR3/>
           <MVGR4/>
           <MVGR5/>
           <VPZUO/>
           <VGTYP/>
           <RFVGTYP/>
           <KOSTL/>
           <KOKRS/>
           <PAOBJNR/>
           <PRCTR/>
           <PS_PSP_PNR/>
           <AUFNR/>
           <POSNR_PP/>
           <KDAUF/>
           <KDPOS/>
           <VPMAT/>
           <VPWRK/>
           <PRBME/>
           <UMREF/>
           <KNTTP/>
           <KZVBR/>
           <FIPOS/>
           <FISTL/>
           <GEBER/>
           <PCKPF/>
           <BEDAR_LF/>
           <CMPNT/>
           <KCMENG/>
           <KCBRGEW/>
           <KCNTGEW/>
           <KCVOLUM/>
           <UECHA/>
           <CUOBJ/>
           <CUOBJ_CH/>
           <ANZSN/>
           <SERAIL/>
           <KCGEWEI/>
           <KCVOLEH/>
           <SERNR/>
           <ABRLI/>
           <ABART/>
           <ABRVW/>
           <QPLOS/>
           <QTLOS/>
           <NACHL/>
           <MAGRV/>
           <OBJKO/>
           <OBJPO/>
           <AESKD/>
           <SHKZG/>
           <PROSA/>
           <UEPVW/>
           <EMPST/>
           <ABTNR/>
           <KOQUI/>
           <STADAT/>
           <AKTNR/>
           <KNUMH_CH/>
           <PREFE/>
           <EXART/>
           <CLINT/>
           <CHMVS/>
           <ABELN/>
           <ABELP/>
           <LFIMG_FLO/>
           <LGMNG_FLO/>
           <KCMENG_FLO/>
           <KZUMW/>
           <KMPMG/>
           <AUREL/>
           <KPEIN/>
           <KMEIN/>
           <NETPR/>
           <NETWR/>
           <KOWRR/>
           <KZBEW/>
           <MFRGR/>
           <CHHPV/>
           <ABFOR/>
           <ABGES/>
           <MBUHR/>
           <WKTNR/>
           <WKTPS/>
           <J_1BCFOP/>
           <J_1BTAXLW1/>
           <J_1BTAXLW2/>
           <J_1BTXSDC/>
           <SITUA/>
           <RSNUM/>
           <RSPOS/>
           <RSART/>
           <KANNR/>
           <KZFME/>
           <PROFL/>
           <KCMENGVME/>
           <KCMENGVMEF/>
           <KZBWS/>
           <PSPNR/>
           <EPRIO/>
           <RULES/>
           <KZBEF/>
           <MPROF/>
           <EMATN/>
           <LGBZO/>
           <HANDLE/>
           <VERURPOS/>
           <LIFEXPOS/>
           <NOATP/>
           <NOPCK/>
           <RBLVS/>
           <BERID/>
           <BESTQ/>
           <UMBSQ/>
           <UMMAT/>
           <UMWRK/>
           <UMLGO/>
           <UMCHA/>
           <UMBAR/>
           <UMSOK/>
           <SONUM/>
           <USONU/>
           <AKKUR/>
           <AKMNG/>
           <VKGRU/>
           <SHKZG_UM/>
           <INSMK/>
           <KZECH/>
           <FLGWM/>
           <BERKZ/>
           <HUPOS/>
           <NOWAB/>
           <KONTO/>
           <KZEAR/>
           <HSDAT/>
           <VFDAT/>
           <LFGJA/>
           <LFBNR/>
           <LFPOS/>
           <GRUND/>
           <FOBWA/>
           <DLVTP/>
           <EXBWR/>
           <BPMNG/>
           <EXVKW/>
           <CMPRE_FLT/>
           <KZPOD/>
           <LFDEZ/>
           <UMREV/>
           <PODREL/>
           <KZUML/>
           <FKBER/>
           <GRANT_NBR/>
           <KZWSO/>
           <GMCONTROL/>
           <POSTING_CHANGE/>
           <UM_PS_PSP_PNR/>
           <PRE_VL_ETENS/>
           <SPE_GEN_ELIKZ/>
           <SPE_SCRAP_IND/>
           <SPE_AUTH_NUMBER/>
           <SPE_INSPOUT_GUID/>
           <SPE_FOLLOW_UP/>
           <SPE_EXP_DATE_EXT/>
           <SPE_EXP_DATE_INT/>
           <SPE_AUTH_COMPLET/>
           <ORMNG/>
           <SPE_ATP_TMSTMP/>
           <SPE_ORIG_SYS/>
           <SPE_LIEFFZ/>
           <SPE_IMWRK/>
           <SPE_LIFEXPOS2/>
           <SPE_EXCEPT_CODE/>
           <SPE_KEEP_QTY/>
           <SPE_ALTERNATE/>
           <SPE_MAT_SUBST/>
           <SPE_STRUC/>
           <SPE_EXP_DATE_EXT_B/>
           <STK_SEGMENT/>
           <REQ_SEGMENT/>
           <MATNR_LONG/>
           <MATWA_LONG/>
           <VPMAT_LONG/>
           <EMATN_LONG/>
           <UMMAT_LONG/>
           <VBTYV_LONG/>
           <VGTYP_LONG/>
           <RFVGTYP_LONG/>
        </item>
     </RESULT_DELIVERY_ITEM>
     <RETURN>
        <item>
           <TYPE/>
           <ID/>
           <NUMBER/>
           <MESSAGE/>
           <LOG_NO/>
           <LOG_MSG_NO/>
           <MESSAGE_V1/>
           <MESSAGE_V2/>
           <MESSAGE_V3/>
           <MESSAGE_V4/>
           <PARAMETER/>
           <ROW/>
           <FIELD/>
           <SYSTEM/>
        </item>
     </RETURN>
  </ns0:ZFM_CUSTOMER_DELIVERY_LIST>`;
 
   axios
     .post(requestURL, bodyRequest, config)
     .then(function (response) {
      res.send({data:response.data});
     })
     .catch(function (error) {
       console.log(error);
     });
 });
 
//@type      POST
//@route     /deliverydetail
//@desc      route to get deliverydetail data
//@access    PUBLIC
router.post("/deliverydetail", (req, res) => {
   const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_delivery_detail`;
   //90000000
   const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
  <ns0:ZFM_CUST_DELIVERY_DETAIL xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
     <DOCUMENT_NO>${req.body.delivery_document_no}</DOCUMENT_NO>
     <IT_DELIVERY_DETAIL>
        <item>
           <MANDT/>
           <VBELN/>
           <POSNR/>
           <PSTYV/>
           <ERNAM/>
           <ERZET/>
           <ERDAT/>
           <MATNR/>
           <MATWA/>
           <MATKL/>
           <WERKS/>
           <LGORT/>
           <CHARG/>
           <LICHN/>
           <KDMAT/>
           <PRODH/>
           <LFIMG/>
           <MEINS/>
           <VRKME/>
           <UMVKZ/>
           <UMVKN/>
           <NTGEW/>
           <BRGEW/>
           <GEWEI/>
           <VOLUM/>
           <VOLEH/>
           <KZTLF/>
           <UEBTK/>
           <UEBTO/>
           <UNTTO/>
           <CHSPL/>
           <FAKSP/>
           <MBDAT/>
           <LGMNG/>
           <ARKTX/>
           <LGPBE/>
           <VBELV/>
           <POSNV/>
           <VBTYV/>
           <VGSYS/>
           <VGBEL/>
           <VGPOS/>
           <UPFLU/>
           <UEPOS/>
           <FKREL/>
           <LADGR/>
           <TRAGR/>
           <KOMKZ/>
           <LGNUM/>
           <LISPL/>
           <LGTYP/>
           <LGPLA/>
           <BWTEX/>
           <BWART/>
           <BWLVS/>
           <KZDLG/>
           <BDART/>
           <PLART/>
           <MTART/>
           <XCHPF/>
           <XCHAR/>
           <VGREF/>
           <POSAR/>
           <BWTAR/>
           <SUMBD/>
           <MTVFP/>
           <EANNR/>
           <GSBER/>
           <VKBUR/>
           <VKGRP/>
           <VTWEG/>
           <SPART/>
           <GRKOR/>
           <FMENG/>
           <ANTLF/>
           <VBEAF/>
           <VBEAV/>
           <STAFO/>
           <WAVWR/>
           <KZWI1/>
           <KZWI2/>
           <KZWI3/>
           <KZWI4/>
           <KZWI5/>
           <KZWI6/>
           <SOBKZ/>
           <AEDAT/>
           <EAN11/>
           <KVGR1/>
           <KVGR2/>
           <KVGR3/>
           <KVGR4/>
           <KVGR5/>
           <MVGR1/>
           <MVGR2/>
           <MVGR3/>
           <MVGR4/>
           <MVGR5/>
           <VPZUO/>
           <VGTYP/>
           <RFVGTYP/>
           <KOSTL/>
           <KOKRS/>
           <PAOBJNR/>
           <PRCTR/>
           <PS_PSP_PNR/>
           <AUFNR/>
           <POSNR_PP/>
           <KDAUF/>
           <KDPOS/>
           <VPMAT/>
           <VPWRK/>
           <PRBME/>
           <UMREF/>
           <KNTTP/>
           <KZVBR/>
           <FIPOS/>
           <FISTL/>
           <GEBER/>
           <PCKPF/>
           <BEDAR_LF/>
           <CMPNT/>
           <KCMENG/>
           <KCBRGEW/>
           <KCNTGEW/>
           <KCVOLUM/>
           <UECHA/>
           <CUOBJ/>
           <CUOBJ_CH/>
           <ANZSN/>
           <SERAIL/>
           <KCGEWEI/>
           <KCVOLEH/>
           <SERNR/>
           <ABRLI/>
           <ABART/>
           <ABRVW/>
           <QPLOS/>
           <QTLOS/>
           <NACHL/>
           <MAGRV/>
           <OBJKO/>
           <OBJPO/>
           <AESKD/>
           <SHKZG/>
           <PROSA/>
           <UEPVW/>
           <EMPST/>
           <ABTNR/>
           <KOQUI/>
           <STADAT/>
           <AKTNR/>
           <KNUMH_CH/>
           <PREFE/>
           <EXART/>
           <CLINT/>
           <CHMVS/>
           <ABELN/>
           <ABELP/>
           <LFIMG_FLO/>
           <LGMNG_FLO/>
           <KCMENG_FLO/>
           <KZUMW/>
           <KMPMG/>
           <AUREL/>
           <KPEIN/>
           <KMEIN/>
           <NETPR/>
           <NETWR/>
           <KOWRR/>
           <KZBEW/>
           <MFRGR/>
           <CHHPV/>
           <ABFOR/>
           <ABGES/>
           <MBUHR/>
           <WKTNR/>
           <WKTPS/>
           <J_1BCFOP/>
           <J_1BTAXLW1/>
           <J_1BTAXLW2/>
           <J_1BTXSDC/>
           <SITUA/>
           <RSNUM/>
           <RSPOS/>
           <RSART/>
           <KANNR/>
           <KZFME/>
           <PROFL/>
           <KCMENGVME/>
           <KCMENGVMEF/>
           <KZBWS/>
           <PSPNR/>
           <EPRIO/>
           <RULES/>
           <KZBEF/>
           <MPROF/>
           <EMATN/>
           <LGBZO/>
           <HANDLE/>
           <VERURPOS/>
           <LIFEXPOS/>
           <NOATP/>
           <NOPCK/>
           <RBLVS/>
           <BERID/>
           <BESTQ/>
           <UMBSQ/>
           <UMMAT/>
           <UMWRK/>
           <UMLGO/>
           <UMCHA/>
           <UMBAR/>
           <UMSOK/>
           <SONUM/>
           <USONU/>
           <AKKUR/>
           <AKMNG/>
           <VKGRU/>
           <SHKZG_UM/>
           <INSMK/>
           <KZECH/>
           <FLGWM/>
           <BERKZ/>
           <HUPOS/>
           <NOWAB/>
           <KONTO/>
           <KZEAR/>
           <HSDAT/>
           <VFDAT/>
           <LFGJA/>
           <LFBNR/>
           <LFPOS/>
           <GRUND/>
           <FOBWA/>
           <DLVTP/>
           <EXBWR/>
           <BPMNG/>
           <EXVKW/>
           <CMPRE_FLT/>
           <KZPOD/>
           <LFDEZ/>
           <UMREV/>
           <PODREL/>
           <KZUML/>
           <FKBER/>
           <GRANT_NBR/>
           <KZWSO/>
           <GMCONTROL/>
           <POSTING_CHANGE/>
           <UM_PS_PSP_PNR/>
           <PRE_VL_ETENS/>
           <SPE_GEN_ELIKZ/>
           <SPE_SCRAP_IND/>
           <SPE_AUTH_NUMBER/>
           <SPE_INSPOUT_GUID/>
           <SPE_FOLLOW_UP/>
           <SPE_EXP_DATE_EXT/>
           <SPE_EXP_DATE_INT/>
           <SPE_AUTH_COMPLET/>
           <ORMNG/>
           <SPE_ATP_TMSTMP/>
           <SPE_ORIG_SYS/>
           <SPE_LIEFFZ/>
           <SPE_IMWRK/>
           <SPE_LIFEXPOS2/>
           <SPE_EXCEPT_CODE/>
           <SPE_KEEP_QTY/>
           <SPE_ALTERNATE/>
           <SPE_MAT_SUBST/>
           <SPE_STRUC/>
           <SPE_EXP_DATE_EXT_B/>
           <STK_SEGMENT/>
           <REQ_SEGMENT/>
           <MATNR_LONG/>
           <MATWA_LONG/>
           <VPMAT_LONG/>
           <EMATN_LONG/>
           <UMMAT_LONG/>
           <VBTYV_LONG/>
           <VGTYP_LONG/>
           <RFVGTYP_LONG/>
        </item>
     </IT_DELIVERY_DETAIL>
  </ns0:ZFM_CUST_DELIVERY_DETAIL>`;

  axios
    .post(requestURL, bodyRequest, config)
    .then(function (response) {
      res.send({data:response.data});
    })
    .catch(function (error) {
      console.log(error);
    });
});

// FINANCIAL SHEET

//@type      POST
//@route     /paymentaging
//@desc      route to get paymentaging data
//@access    PUBLIC
router.post("/paymentaging", (req, res) => {
   const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_payment_aging`;
   const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
  <ns0:ZFM_CUST_FS_PAYMENT_AGING xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
     <CUSTOMER_NO>${req.body.customer_id}</CUSTOMER_NO>
     <IT_LINEITEM>
        <item>
           <COMP_CODE/>
           <CUSTOMER/>
           <SP_GL_IND/>
           <CLEAR_DATE/>
           <CLR_DOC_NO/>
           <ALLOC_NMBR/>
           <FISC_YEAR/>
           <DOC_NO/>
           <ITEM_NUM/>
           <PSTNG_DATE/>
           <DOC_DATE/>
           <ENTRY_DATE/>
           <CURRENCY/>
           <LOC_CURRCY/>
           <REF_DOC_NO/>
           <DOC_TYPE/>
           <FIS_PERIOD/>
           <POST_KEY/>
           <DB_CR_IND/>
           <BUS_AREA/>
           <TAX_CODE/>
           <LC_AMOUNT/>
           <AMT_DOCCUR/>
           <LC_TAX/>
           <TX_DOC_CUR/>
           <ITEM_TEXT/>
           <BRANCH/>
           <BLINE_DATE/>
           <PMNTTRMS/>
           <DSCT_DAYS1/>
           <DSCT_DAYS2/>
           <NETTERMS/>
           <DSCT_PCT1/>
           <DSCT_PCT2/>
           <DISC_BASE/>
           <DSC_AMT_LC/>
           <DSC_AMT_DC/>
           <PYMT_METH/>
           <PMNT_BLOCK/>
           <FIXEDTERMS/>
           <INV_REF/>
           <INV_YEAR/>
           <INV_ITEM/>
           <DUNN_BLOCK/>
           <DUNN_KEY/>
           <LAST_DUNN/>
           <DUNN_LEVEL/>
           <DUNN_AREA/>
           <DOC_STATUS/>
           <NXT_DOCTYP/>
           <VAT_REG_NO/>
           <REASON_CDE/>
           <PMTMTHSUPL/>
           <REF_KEY_1/>
           <REF_KEY_2/>
           <T_CURRENCY/>
           <AMOUNT/>
           <NET_AMOUNT/>
           <NAME/>
           <NAME_2/>
           <NAME_3/>
           <NAME_4/>
           <POSTL_CODE/>
           <CITY/>
           <COUNTRY/>
           <STREET/>
           <PO_BOX/>
           <POBX_PCD/>
           <POBK_CURAC/>
           <BANK_ACCT/>
           <BANK_KEY/>
           <BANK_CTRY/>
           <TAX_NO_1/>
           <TAX_NO_2/>
           <TAX/>
           <EQUAL_TAX/>
           <REGION/>
           <CTRL_KEY/>
           <INSTR_KEY/>
           <PAYEE_CODE/>
           <LANGU/>
           <BILL_LIFE/>
           <BE_TAXCODE/>
           <BILLTAX_LC/>
           <BILLTAX_FC/>
           <LC_COL_CHG/>
           <COLL_CHARG/>
           <CHGS_TX_CD/>
           <ISSUE_DATE/>
           <USAGEDATE/>
           <BILL_USAGE/>
           <DOMICILE/>
           <DRAWER/>
           <CTRBNK_LOC/>
           <DRAW_CITY1/>
           <DRAWEE/>
           <DRAW_CITY2/>
           <DISCT_DAYS/>
           <DISCT_RATE/>
           <ACCEPTED/>
           <BILLSTATUS/>
           <PRTEST_IND/>
           <BE_DEMAND/>
           <OBJ_TYPE/>
           <REF_DOC/>
           <REF_ORG_UN/>
           <REVERSAL_DOC/>
           <SP_GL_TYPE/>
           <NEG_POSTNG/>
           <REF_DOC_NO_LONG/>
           <BILL_DOC/>
        </item>
     </IT_LINEITEM>
  </ns0:ZFM_CUST_FS_PAYMENT_AGING>`;
 
   axios
     .post(requestURL, bodyRequest, config)
     .then(function (response) {
      res.send({data:response.data});
     })
     .catch(function (error) {
       console.log(error);
     });
 });

//@type      POST
//@route     /debitmemo
//@desc      route to get debitmemo data
//@access    PUBLIC
router.post("/debitmemo", (req, res) => {
   const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_debit_memo`;
  const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
  <ns0:ZFM_CUST_FS_DEBIT_MEMO xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
     <CUSTOMER_ID>${req.body.customer_id}</CUSTOMER_ID>
     <IT_DEBIT_RESULT>
        <item>
           <COMP_CODE/>
           <CUSTOMER/>
           <SP_GL_IND/>
           <CLEAR_DATE/>
           <CLR_DOC_NO/>
           <ALLOC_NMBR/>
           <FISC_YEAR/>
           <DOC_NO/>
           <ITEM_NUM/>
           <PSTNG_DATE/>
           <DOC_DATE/>
           <ENTRY_DATE/>
           <CURRENCY/>
           <LOC_CURRCY/>
           <REF_DOC_NO/>
           <DOC_TYPE/>
           <FIS_PERIOD/>
           <POST_KEY/>
           <DB_CR_IND/>
           <BUS_AREA/>
           <TAX_CODE/>
           <LC_AMOUNT/>
           <AMT_DOCCUR/>
           <LC_TAX/>
           <TX_DOC_CUR/>
           <ITEM_TEXT/>
           <BRANCH/>
           <BLINE_DATE/>
           <PMNTTRMS/>
           <DSCT_DAYS1/>
           <DSCT_DAYS2/>
           <NETTERMS/>
           <DSCT_PCT1/>
           <DSCT_PCT2/>
           <DISC_BASE/>
           <DSC_AMT_LC/>
           <DSC_AMT_DC/>
           <PYMT_METH/>
           <PMNT_BLOCK/>
           <FIXEDTERMS/>
           <INV_REF/>
           <INV_YEAR/>
           <INV_ITEM/>
           <DUNN_BLOCK/>
           <DUNN_KEY/>
           <LAST_DUNN/>
           <DUNN_LEVEL/>
           <DUNN_AREA/>
           <DOC_STATUS/>
           <NXT_DOCTYP/>
           <VAT_REG_NO/>
           <REASON_CDE/>
           <PMTMTHSUPL/>
           <REF_KEY_1/>
           <REF_KEY_2/>
           <T_CURRENCY/>
           <AMOUNT/>
           <NET_AMOUNT/>
           <NAME/>
           <NAME_2/>
           <NAME_3/>
           <NAME_4/>
           <POSTL_CODE/>
           <CITY/>
           <COUNTRY/>
           <STREET/>
           <PO_BOX/>
           <POBX_PCD/>
           <POBK_CURAC/>
           <BANK_ACCT/>
           <BANK_KEY/>
           <BANK_CTRY/>
           <TAX_NO_1/>
           <TAX_NO_2/>
           <TAX/>
           <EQUAL_TAX/>
           <REGION/>
           <CTRL_KEY/>
           <INSTR_KEY/>
           <PAYEE_CODE/>
           <LANGU/>
           <BILL_LIFE/>
           <BE_TAXCODE/>
           <BILLTAX_LC/>
           <BILLTAX_FC/>
           <LC_COL_CHG/>
           <COLL_CHARG/>
           <CHGS_TX_CD/>
           <ISSUE_DATE/>
           <USAGEDATE/>
           <BILL_USAGE/>
           <DOMICILE/>
           <DRAWER/>
           <CTRBNK_LOC/>
           <DRAW_CITY1/>
           <DRAWEE/>
           <DRAW_CITY2/>
           <DISCT_DAYS/>
           <DISCT_RATE/>
           <ACCEPTED/>
           <BILLSTATUS/>
           <PRTEST_IND/>
           <BE_DEMAND/>
           <OBJ_TYPE/>
           <REF_DOC/>
           <REF_ORG_UN/>
           <REVERSAL_DOC/>
           <SP_GL_TYPE/>
           <NEG_POSTNG/>
           <REF_DOC_NO_LONG/>
           <BILL_DOC/>
        </item>
     </IT_DEBIT_RESULT>
  </ns0:ZFM_CUST_FS_DEBIT_MEMO>`;
   axios
     .post(requestURL, bodyRequest, config)
     .then(function (response) {
      res.send({data:response.data});
     })
     .catch(function (error) {
       console.log(error);
     });
 });

//@type      POST
//@route     /creditmemo
//@desc      route to get creditmemo data
//@access    PUBLIC
router.post("/creditmemo", (req, res) => {
   const requestURL = `http://dxktpipo.kaarcloud.com:50000/RESTAdapter/eyuwankg_cust_credit_memo`;
  const bodyRequest = `<?xml version="1.0" encoding="UTF-8"?>
  <ns0:ZFM_CUST_FS_CREDIT_MEMO xmlns:ns0="urn:sap-com:document:sap:rfc:functions">
     <CUSTOMER_ID>${req.body.customer_id}</CUSTOMER_ID>
     <IT_CREDIT_RESULT>
        <item>
           <COMP_CODE/>
           <CUSTOMER/>
           <SP_GL_IND/>
           <CLEAR_DATE/>
           <CLR_DOC_NO/>
           <ALLOC_NMBR/>
           <FISC_YEAR/>
           <DOC_NO/>
           <ITEM_NUM/>
           <PSTNG_DATE/>
           <DOC_DATE/>
           <ENTRY_DATE/>
           <CURRENCY/>
           <LOC_CURRCY/>
           <REF_DOC_NO/>
           <DOC_TYPE/>
           <FIS_PERIOD/>
           <POST_KEY/>
           <DB_CR_IND/>
           <BUS_AREA/>
           <TAX_CODE/>
           <LC_AMOUNT/>
           <AMT_DOCCUR/>
           <LC_TAX/>
           <TX_DOC_CUR/>
           <ITEM_TEXT/>
           <BRANCH/>
           <BLINE_DATE/>
           <PMNTTRMS/>
           <DSCT_DAYS1/>
           <DSCT_DAYS2/>
           <NETTERMS/>
           <DSCT_PCT1/>
           <DSCT_PCT2/>
           <DISC_BASE/>
           <DSC_AMT_LC/>
           <DSC_AMT_DC/>
           <PYMT_METH/>
           <PMNT_BLOCK/>
           <FIXEDTERMS/>
           <INV_REF/>
           <INV_YEAR/>
           <INV_ITEM/>
           <DUNN_BLOCK/>
           <DUNN_KEY/>
           <LAST_DUNN/>
           <DUNN_LEVEL/>
           <DUNN_AREA/>
           <DOC_STATUS/>
           <NXT_DOCTYP/>
           <VAT_REG_NO/>
           <REASON_CDE/>
           <PMTMTHSUPL/>
           <REF_KEY_1/>
           <REF_KEY_2/>
           <T_CURRENCY/>
           <AMOUNT/>
           <NET_AMOUNT/>
           <NAME/>
           <NAME_2/>
           <NAME_3/>
           <NAME_4/>
           <POSTL_CODE/>
           <CITY/>
           <COUNTRY/>
           <STREET/>
           <PO_BOX/>
           <POBX_PCD/>
           <POBK_CURAC/>
           <BANK_ACCT/>
           <BANK_KEY/>
           <BANK_CTRY/>
           <TAX_NO_1/>
           <TAX_NO_2/>
           <TAX/>
           <EQUAL_TAX/>
           <REGION/>
           <CTRL_KEY/>
           <INSTR_KEY/>
           <PAYEE_CODE/>
           <LANGU/>
           <BILL_LIFE/>
           <BE_TAXCODE/>
           <BILLTAX_LC/>
           <BILLTAX_FC/>
           <LC_COL_CHG/>
           <COLL_CHARG/>
           <CHGS_TX_CD/>
           <ISSUE_DATE/>
           <USAGEDATE/>
           <BILL_USAGE/>
           <DOMICILE/>
           <DRAWER/>
           <CTRBNK_LOC/>
           <DRAW_CITY1/>
           <DRAWEE/>
           <DRAW_CITY2/>
           <DISCT_DAYS/>
           <DISCT_RATE/>
           <ACCEPTED/>
           <BILLSTATUS/>
           <PRTEST_IND/>
           <BE_DEMAND/>
           <OBJ_TYPE/>
           <REF_DOC/>
           <REF_ORG_UN/>
           <REVERSAL_DOC/>
           <SP_GL_TYPE/>
           <NEG_POSTNG/>
           <REF_DOC_NO_LONG/>
           <BILL_DOC/>
        </item>
     </IT_CREDIT_RESULT>
  </ns0:ZFM_CUST_FS_CREDIT_MEMO>`;
   axios
     .post(requestURL, bodyRequest, config)
     .then(function (response) {
         res.send({data:response.data});
     })
     .catch(function (error) {
       console.log(error);
     });
 });

router.get("/", (req, res) => res.send("Customer portal"));

module.exports = router;
