const vendorPaymentAndAgingTableHead={
  "AGING":"Aging Days",
  "COMP_CODE": "Company Code",
  "VENDOR": "Vendor No",
  "SP_GL_IND": "Special G/L Indicator",
  "CLEAR_DATE": "Clearing Date",
  "CLR_DOC_NO": "Clearing Document Doc",
  "ALLOC_NMBR": "Assignment No",
  "FISC_YEAR": "Fiscal Year",
  "DOC_NO": "Document No",
  "ITEM_NUM": "Line Item Num",
  "PSTNG_DATE": "Posting Date",
  "DOC_DATE": "Document Date",
  "ENTRY_DATE": "Entry Date",
  "CURRENCY": "Currency Key",
  "LOC_CURRCY": "Local Currency",
  "REF_DOC_NO": "Reference Doc No",
  "DOC_TYPE": "Document Tyoe",
  "FIS_PERIOD": "Fiscal Period",
  "POST_KEY": "Posting Key",
  "DB_CR_IND": "Debit/Credit Indicator",
  "BUS_AREA": "Business Area",
  "TAX_CODE": "Tax Code",
  "LC_AMOUNT": "Local Currency Amount",
  "AMT_DOCCUR": "Amount Document Currency",
  "LC_TAX": "Tax Amount",
  "TX_DOC_CUR": "Tax Amount Document Currency",
  "ITEM_TEXT": "Item Text",
  "BRANCH": "Branch",
  "BLINE_DATE": "Base Line Date",
  "PMNTTRMS": "Terms Of Payment Key",
  "DSCT_DAYS1": "Cash Discount Days 1",
  "DSCT_DAYS2": "Cash Discount Days 2",
  "NETTERMS": "Net Payment Terms Period",
  "DSCT_PCT1": "Cash Discount % 1",
  "DSCT_PCT2": "Cash Discount % 2",
  "DISC_BASE": "Amount Eligible For Cash Discount",
  "DSC_AMT_LC": "Cash Discount Amount in Local Currency",
  "DSC_AMT_DC": "Cash Discount Amount in Document Currency",
  "PYMT_METH": "Payment Method",
  "PMNT_BLOCK": "Payment Block Key",
  "FIXEDTERMS": "Fixed Payment Terms",
  "INV_REF": "Invoice Reference",
  "INV_YEAR": "Invoice Year",
  "INV_ITEM": "Line Item",
  "DUNN_BLOCK": "Dunning Block",
  "DUNN_KEY": "Dunning key",
  "LAST_DUNN": "Last Dunning Notice",
  "DUNN_LEVEL": "Dunning Level",
  "DUNN_AREA": "Dunning Area",
  "DOC_STATUS": "Document Status",
  "NXT_DOCTYP": "Follow-On Doc Type",
  "W_TAX_CODE": 'Withholding Tax Code' ,
  "W_TAX_BASE": 'Withholding Tax Base Amount' ,
  "WI_TAX_AMT":  'Withholding Tax Amount (in Document Currency)' ,
  "VAT_REG_NO": "VAT Registration No",
  "EXEMPT_NO": "Tax Exemption No",
  "W_TAX_EXPT": "Withholding Tax Exempt Amount",
  "REASON_CDE": "Reason code for payments",
  "PMTMTHSUPL": "Payment method Supplement",
  "REF_KEY_1": "Business Partner Reference Key",
  "REF_KEY_2": "Business Partner Reference Key 2",
  "T_CURRENCY": "Update Currency",
  "AMOUNT": "Amount",
  "NET_AMOUNT": "Net Amount",
  "NAME": "Name",
  "NAME_2": "Name 2",
  "NAME_3": "Name 3",
  "NAME_4": "Name 4",
  "POSTL_CODE": "Postal Code",
  "CITY": "City",
  "COUNTRY": "Country",
  "STREET": "Street",
  "PO_BOX": "PO Box",
  "POBX_PCD": "P.O Box Postal Code",
  "POBK_CURAC": "Account No",
  "BANK_ACCT": "Bank Account No",
  "BANK_KEY": "Bank Keys",
  "BANK_CTRY": "Bank Country Key",
  "TAX_NO_1": "Tax No 1",
  "TAX_NO_2": "Tax No 2",
  "TAX": "Tax",
  "EQUAL_TAX": "Equalization Tax",
  "REGION": "Region",
  "CTRL_KEY": "Control Key",
  "INSTR_KEY": "Instruction Key",
  "PAYEE_CODE": "Payee code",
  "LANGU": "Language",
  "BILL_LIFE": "Bill Life",
  "BE_TAXCODE": "Bill Tax Code",
  "BILLTAX_LC": "Exchange Bill Tax in Local Currency",
  "BILLTAX_FC": "Exchange Bill Tax in Foreign Currency",
  "LC_COL_CHG": "Exchange Bill Collection Charge",
  "COLL_CHARG": "Exchange Bill Collection in Document No",
  "CHGS_TX_CD": "Tax Code for bill of exchange charges",
  "ISSUE_DATE": "Issue Date",
  "USAGEDATE": "Usage Date",
  "BILL_USAGE": "Bill Usage",
  "DOMICILE": "Bank Address",
  "DRAWER": "Exchange Name Drawer",
  "CTRBNK_LOC": "State Central Bank Location",
  "DRAW_CITY1": "Exchange Bill Drawer City",
  "DRAWEE": "Exchange Bill Drawee",
  "DRAW_CITY2": "Excange Bill Drawer City 2",
  "DISCT_DAYS": "Discount Days",
  "DISCT_RATE": "Discount Rate",
  "ACCEPTED": "Accepted Bill Exchange",
  "BILLSTATUS": "Bill Status",
  "PRTEST_IND": "Exchange Protest Indicatpr",
  "BE_DEMAND": "Bill on Demand",
  "OBJ_TYPE": "Reference Procedure",
  "REF_DOC": "Refernce Document No",
  "REF_ORG_UN": "Reference Organisation Unit",
  "REVERSAL_DOC": "Reversal Document No",
  "SP_GL_TYPE": "Special G/L Transaction Type",
  "NEG_POSTNG": "Negative Posting",
  "REF_DOC_NO_LONG": "Reference Doc No Long"
}

export default vendorPaymentAndAgingTableHead;