const vendorGoodsReceiptTableHead={
  "MAT_DOC": "Material Document No",
  "DOC_YEAR": "Material Document Year",
  "MATDOC_ITM": "Material Document Item",
  "MATERIAL": "Material No",
  "PLANT": "Plant",
  "STGE_LOC": "Storage Location",
  "BATCH": "Batch",
  "MOVE_TYPE": "Movement Type",
  "STCK_TYPE": "Stock Type",
  "SPEC_STOCK": "Special Stock Indicator",
  "VENDOR": "Vendor Account No",
  "CUSTOMER": "Customer Account No",
  "SALES_ORD": "Sales Order No",
  "S_ORD_ITEM": "Sales Order Item No",
  "SCHED_LINE": "Delivery Schedule for Sales Order",
  "VAL_TYPE": "Valuation Type",
  "ENTRY_QNT": "Entry Quantity",
  "ENTRY_UOM": "Entry unit",
  "ENTRY_UOM_ISO": "Entry Unit ISO",
  "PO_PR_QNT": "Purchase Order price unit",
  "ORDERPR_UN": "Order Price unit",
  "ORDERPR_UN_ISO": "ISO code for unit of measurement",
  "PO_NUMBER": "Purchase order Number",
  "PO_ITEM": "Pruchase order Item",
  "SHIPPING": "Shipping Instructions",
  "COMP_SHIP": "Compilance with Shipping Instructions",
  "NO_MORE_GR": "Delivery Completed Indicator",
  "ITEM_TEXT": "Description",
  "GR_RCPT": "Goods Recipent",
  "UNLOAD_PT": "Unloading Point",
  "COSTCENTER": "Cost Center",
  "ORDERID": "Order Id",
  "ORDER_ITNO": "Order Item No",
  "CALC_MOTIVE": "Accounting Indicator",
  "ASSET_NO": "Asset No",
  "SUB_NUMBER": "Asset Sub No ",
  "RESERV_NO": "Reservation No",
  "RES_ITEM": "Reservation Item No",
  "RES_TYPE": "Record Type",
  "WITHDRAWN": "Final Issue",
  "MOVE_MAT": "Receiving MAterial",
  "MOVE_PLANT": "Receiving Plant",
  "MOVE_STLOC": "Receiving Storage Location",
  "MOVE_BATCH": "Receiving Batch",
  "MOVE_VAL_TYPE": "Receiving Valuation Type",
  "MVT_IND": "Movement Indicator",
  "MOVE_REAS": "Movement Reason",
  "RL_EST_KEY": "Internal Key for Real Estate",
  "REF_DATE": "Reference Doc Date",
  "COST_OBJ": "Cost Object",
  "PROFIT_SEGM_NO": "Profit Segment No",
  "PROFIT_CTR": "Profit Center",
  "WBS_ELEM": "Work BreakDown Structure Element",
  "NETWORK": "Network",
  "ACTIVITY": "Activity",
  "PART_ACCT": "Partner Account No",
  "AMOUNT_LC": "Amount in Local currency ",
  "AMOUNT_SV": "Sales Amount in Local Currency",
  "CURRENCY": "Currency",
  "CURRENCY_ISO": "Currency ISO",
  "REF_DOC_YR": "Refernce Doc Year",
  "REF_DOC": "Reference Document",
  "REF_DOC_IT": "Reference Document Item",
  "EXPIRYDATE": "Expiry Date",
  "PROD_DATE": "Manufacture Date",
  "FUND": "Fund",
  "FUNDS_CTR": "Fund Center",
  "CMMT_ITEM": "Commitment Item",
  "VAL_SALES_ORD": "Valuated Sales Order Stock No",
  "VAL_S_ORD_ITEM": "Valuated Sales Order Stock Item",
  "VAL_WBS_ELEM": "Work BreakDown Structure",
  "CO_BUSPROC": "Business Process",
  "ACTTYPE": "Activity Type",
  "SUPPL_VEND": "Supplying Vendor",
  "X_AUTO_CRE": "Item Automatically Creater",
  "MATERIAL_EXTERNAL": "Material External No",
  "MATERIAL_GUID": "Material External GUID",
  "MATERIAL_VERSION": "Material Version",
  "MOVE_MAT_EXTERNAL": "Material Long External No",
  "MOVE_MAT_GUID": "Material Long Exteranl GUID",
  "MOVE_MAT_VERSION": "Material Long Version",
  "GRANT_NBR": "Grant",
  "CMMT_ITEM_LONG": "Commitment Item",
  "FUNC_AREA_LONG": "Functional Area",
  "LINE_ID": "unique Identification of Document Line",
  "PARENT_ID": "Identification of Superior Lien",
  "LINE_DEPTH": "Heirarchy Level of line in document",
  "BUDGET_PERIOD": "Budget Period",
  "EARMARKED_NUMBER": "Emarked Fund Document No",
  "EARMARKED_ITEM": "Emarked Fund Document Item",
  "STK_SEGMENT": "Stock Segement",
  "MATERIAL_LONG": "Material Long",
  "MOVE_MAT_LONG": "Material Issue No"
}

export default vendorGoodsReceiptTableHead;