const invoiceDetailsTableHead={
  "MANDT": "Client",
  "VBELN": "Billing Document",
  "FKART": "Billing Type",
  "FKTYP": "Billing Category",
  "VBTYP": "SD document category",
  "WAERK": "SD document currency",
  "VKORG": "Sales Organization",
  "VTWEG": "Distribution Channel",
  "KALSM": "Sales and Distribution:",
  "KNUMV": "No of Document Condition",
  "VSBED": "Shipping Conditions",
  "FKDAT": "Billing Date",
  "BELNR": "Accouting Document No",
  "GJAHR": "Fiscal Year",
  "POPER": "Posting Period",
  "KONDA": "Price Group",
  "KDGRP": "Customer Group",
  "BZIRK": "Sales District",
  "PLTYP": "Price List Type",
  "INCO1": "Incoterms 1",
  "INCO2": "Incoterms 2",
  "EXPKZ": "Export Indicator",
  "RFBSK": "Transfer to Accounting Status",
  "MRNKZ": "Manual Invoice Maintenance",
  "KURRF": "Exchange Rate",
  "CPKUR": "Exchange Rate Setting",
  "VALTG": "Addition value days",
  "VALDT": "Fixed Value Date",
  "ZTERM": "Payment Key Term",
  "ZLSCH": "Payment Method",
  "KTGRD": "Account Assignment Group",
  "LAND1": "Country Of Destination",
  "REGIO": "Region",
  "COUNC": "Country Code",
  "CITYC": "City Code",
  "BUKRS": "Company Code",
  "TAXK1": "Tax Classification 1",
  "TAXK2": "Tax Classificaiton 2",
  "TAXK3": "Tax Classification 3",
  "TAXK4": "Tax Classificiation 4",
  "TAXK5": "Tax Classification 5",
  "TAXK6": "Tax Classificiation 6",
  "TAXK7": "Tax Classificiation 7",
  "TAXK8": "Tax Classification 8",
  "TAXK9": "Tax Classification 9",
  "NETWR": "Net Value",
  "ZUKRI": "Combination Criteria",
  "ERNAM": "Creator Name",
  "ERZET": "Entry Time",
  "ERDAT": "Entry Date",
  "STAFO": "Statistics update",
  "KUNRG": "Payer",
  "KUNAG": "Sold to party",
  "MABER": "During Area",
  "STWAE": "Statistics Currency",
  "EXNUM": "No of Foreing Trade",
  "STCEG": "VAT Registration No",
  "AEDAT": "Date Of Last Change",
  "SFAKN": "Cancelled Billing Document No",
  "KNUMA": "Agreement",
  "FKART_RL": "Invoice List Type",
  "FKDAT_RL": "Billing Date",
  "KURST": "Exchange Rate Type",
  "MSCHL": "Dunning Key",
  "MANSP": "Dunning Block",
  "SPART": "Division",
  "KKBER": "Credit Control Area",
  "KNKLI": "Customer Account No",
  "CMWAE": "Currency Key of Credit Control Area",
  "CMKUF": "Credit data Exchange Rate",
  "HITYP_PR": "Hierarchy type of pricing",
  "BSTNK_VF": "Customer Purchase Order No",
  "VBUND": "Trading partner company Id",
  "FKART_AB": "Accrual Billing type",
  "KAPPL": "Application",
  "LANDTX": "Tax Departure Country",
  "STCEG_H": "Origin Sales Tax Id",
  "STCEG_L": "Sales Tax Id Country",
  "XBLNR": "Reference Document No",
  "ZUONR": "Assignment No",
  "MWSBK": "Tax Amount in Document Currency",
  "LOGSYS": "Logical System",
  "FKSTO": "Billing Document",
  "XEGDR": "Indicator Triangular deal",
  "RPLNR": "No of payment Card Plan",
  "LCNUM": "Financial Doc",
  "J_1AFITP": "Tax Type",
  "KURRF_DAT": "Translation Date",
  "AKWAE": "Currency key for letter-of-credit procg in foreign trade",
  "AKKUR": "Exchange key for letter-of-credit procg in foreign trade",
  "KIDNO": "Payment Reference",
  "BVTYP": "Partner Bank Type",
  "NUMPG": "No Of Pages Of Invoice",
  "BUPLA": "Business Place",
  "VKONT": "Contract Account Number",
  "FKK_DOCSTAT": "Additional Status for Transfer to Fin. Account",
  "NRZAS": "Character Field",
  "SPE_BILLING_IND": "EWM Billing Indicator",
  "VTREF": "Reference Specification",
  "FK_SOURCE_SYS": "Source System",
  "FKTYP_CRM": "Billing Category in CRM",
  "STGRD": "Reason For Reversal",
  "VBTYP_EXT": "Extensions of SD Document Category",
  "J_1TPBUPL": "Branch Code",
  "INCOV": "Incoterms Location 1",
  "INCO2_L": "Incoterms Location 2",
  "INCO3_L": "Incoterms Location 3",
  "DPC_REL": "DPC Relevant",
  "MNDID": "Unique Refernce to Mandate for each Payee",
  "PAY_TYPE": "Payment Type",
  "SEPON": "SEPA Relevance",
  "MNDVG": "SEPA Relevance 2",
  "SPPAYM": "Payment Form for Special Payment Method",
  "SPPORD": "Sales Order for Special Payment Method"
}

export default invoiceDetailsTableHead;