export var CustomerProfileHeaders: any = [
  {
    key: 'NAME_2',
    title: 'Name',
    value: '',
  },
  {
    key: 'CUSTOMER',
    title: 'Customer Number',
    value: '',
  },
  {
    key: 'CITY',
    title: 'City',
    value: '',
  },
  {
    key: 'COMP_CODE',
    title: 'Company Code',
    value: '',
  },
  {
    key: 'NAME',
    title: 'Name 1',
    value: '',
  },
  {
    key: 'NAME_3',
    title: 'Name 3',
    value: '',
  },
  {
    key: 'NAME_4',
    title: 'Name 4',
    value: '',
  },
  {
    key: 'DISTRICT',
    title: 'District',
    value: '',
  },
  {
    key: 'PO_BOX',
    title: 'PO Box',
    value: '',
  },
  {
    key: 'POBX_PCD',
    title: 'P.O. Box Postal Code',
    value: '',
  },
  {
    key: 'POSTL_CODE',
    title: 'Postal Code',
    value: '',
  },
  {
    key: 'REGION',
    title: 'Region',
    value: '',
  },
  {
    key: 'COUNTYCODE',
    title: 'Country Code',
    value: '',
  },
  {
    key: 'CITY_CODE',
    title: 'City Code',
    value: '',
  },
  {
    key: 'STREET',
    title: 'Street',
    value: '',
  },
  {
    key: 'TELEPHONE',
    title: 'Telephone',
    value: '',
  },
  {
    key: 'COUNTRY',
    title: 'Country',
    value: '',
  },
  {
    key: 'POBX_CTY',
    title: 'PO Box city',
    value: '',
  },
  {
    key: 'LANGU',
    title: 'Language key',
    value: '',
  },
  {
    key: 'SORT_FLD',
    title: 'Sort field',
    value: '',
  },
  {
    key: 'MATCHCODE1',
    title: 'Search Term 1',
    value: '',
  },
  {
    key: 'MATCHCODE2',
    title: 'Search Term 2',
    value: '',
  },
  {
    key: 'MATCHCODE3',
    title: 'Search Term 3',
    value: '',
  },
  {
    key: 'FORMOFADDR',
    title: 'Title',
    value: '',
  },
  {
    key: 'TELEBOX',
    title: 'Telebox number',
    value: '',
  },
  {
    key: 'TELEPHONE2',
    title: 'Second telephone number',
    value: '',
  },
  {
    key: 'TELETEX',
    title: 'Teletex number',
    value: '',
  },
  {
    key: 'TELEX',
    title: 'Telex number',
    value: '',
  },
  {
    key: 'TRANSPZONE',
    title: 'Transportation zone',
    value: '',
  },
  {
    key: 'NIELSEN_ID',
    title: 'Nielsen ID',
    value: '',
  },
  {
    key: 'CLERK',
    title: 'Accounting clerk',
    value: '',
  },
  {
    key: 'HD_OFFICE',
    title: 'Head office Acc No',
    value: '',
  },
  {
    key: 'ALT_PAYER',
    title: 'Account number',
    value: '',
  },
  {
    key: 'CUVD_CLEAR',
    title: ' Clearing between customer and vendor',
    value: '',
  },
  {
    key: 'PMNTTRMS',
    title: 'Terms of Payment Key',
    value: '',
  },
  {
    key: 'ACT_AT_CUS',
    title: 'Our account number at customer',
    value: '',
  },
  {
    key: 'CUST_USER',
    title: 'User at customer',
    value: '',
  },
  {
    key: 'BUYING_GRP',
    title: 'Buying Group Acc no',
    value: '',
  },
  {
    key: 'INTERNET',
    title: 'Internet address',
    value: '',
  },
  {
    key: 'FAX',
    title: 'fax number',
    value: '',
  },
  {
    key: 'PAYMENT_METHODS',
    title: 'Payment Methods',
    value: '',
  },
  {
    key: 'TEL',
    title: 'Telephone number',
    value: '',
  },
  { key: 'ACC_1_TIME', title: 'Company Code', value: '' },
  { key: 'ADDRESS', title: 'Address', value: '' },
  { key: 'ORDR_BLK_G', title: 'Centeral order block', value: '' },
  { key: 'EXPR_STAT', title: 'Express Train Station', value: '' },
  { key: 'TRAIN_STAT', title: 'Train Station', value: '' },
  { key: 'LOC_NO_1', title: 'International location no 1', value: '' },
  { key: 'LOC_NO_2', title: 'International location no 1', value: '' },
  { key: 'AUTH_GROUP', title: 'Authorization group', value: '' },
  { key: 'INDUSTRY', title: 'Industru', value: '' },
  { key: 'CHK_DIGIT', title: 'Check digit', value: '' },
  { key: 'DATA_LINE', title: 'Data communication line', value: '' },
  { key: 'CREAT_DATE', title: 'create date', value: '' },
  { key: 'ENTERED_BY', title: 'Entered by', value: '' },
  { key: 'UNLOAD_PT', title: 'unloading points', value: '' },
  { key: 'BILL_BLK_G', title: 'central billing block', value: '' },
  { key: 'FISK_ADDR', title: 'fiscal address', value: '' },
  { key: 'WORK_TIME', title: 'work time', value: '' },
  { key: 'ALT_PAYER', title: 'Acc No of Alternate player', value: '' },
  { key: 'GROUPKEY', title: 'Group key', value: '' },
  { key: 'ACCNT_GRP', title: 'Customer Account Group', value: '' },
  { key: 'CLASSIFIC', title: 'Customer classification', value: '' },
  { key: 'VENDOR_NO', title: 'Vendor No', value: '' },
  { key: 'DELI_BLK_G', title: 'delivery block', value: '' },
  { key: 'LOC_CODE', title: 'City Coordinates', value: '' },
  { key: 'DEL_FLAG_G', title: 'Centeral Deletion Flag', value: '' },
  { key: 'REG_MARKET', title: 'Regional market', value: '' },
  { key: 'PSTG_BLK_G', title: 'Centeral posting block', value: '' },
  { key: 'TAX_NO_1', title: 'Tax No 1', value: '' },
  { key: 'TAX_NO_2', title: 'Tax No 2', value: '' },
  { key: 'EQUAL_TAX', title: 'Equalization tax', value: '' },
  { key: 'SLS_PUR_TX', title: 'Liable for VAT', value: '' },
  {
    key: 'PAYER_DOC',
    title: 'is alternated player allowed',
    value: '',
  },
  { key: 'TRADE_ID', title: 'trading parter id', value: '' },
  { key: 'VAT_REG_NO', title: 'Vat Register no', value: '' },
  { key: 'COMPETITOR', title: 'Competition', value: '' },
  { key: 'SLSPARTNER', title: 'Sales partner', value: '' },
  { key: 'PROSPECT', title: 'Sales prospect', value: '' },
  { key: 'CUSTTYPE_4', title: 'Customer type', value: '' },
  { key: 'DFLT_SP', title: 'Sold for party Id', value: '' },
  { key: 'LEGALSTAT', title: 'Legal Status', value: '' },
  { key: 'IND_CODE_1', title: 'Industry code 1', value: '' },
  { key: 'IND_CODE_2', title: 'Industry code 2', value: '' },
  { key: 'IND_CODE_3', title: 'Industry code 3', value: '' },
  { key: 'IND_CODE_4', title: 'Industry code 4', value: '' },
  { key: 'IND_CODE_5', title: 'Industry code 5', value: '' },
  { key: 'INITCONTCT', title: 'Initial Contact', value: '' },
  { key: 'ANN_SALES', title: 'Currency Amount', value: '' },
  { key: 'SALES_YEAR', title: 'Sales Year', value: '' },
  { key: 'CURRENCY', title: 'Currency', value: '' },
  { key: 'CURRENCY_ISO', title: 'Currency ISO', value: '' },
  { key: 'EMPLOYEES', title: 'no of employees', value: '' },
  { key: 'EMPL_YEAR', title: 'employees given year', value: '' },
  { key: 'ATTRIBUTE', title: 'Attribute 1', value: '' },
  { key: 'ATTRIB_2', title: 'Attribute 2', value: '' },
  { key: 'ATTRIB_3', title: 'Attribute 3', value: '' },
  { key: 'ATTRIB_4', title: 'Attribute 4', value: '' },
  { key: 'ATTRIB_5', title: 'Attribute 5', value: '' },
  { key: 'ATTRIB_6', title: 'Attribute 6', value: '' },
  { key: 'ATTRIB_7', title: 'Attribute 7', value: '' },
  { key: 'ATTRIB_8', title: 'Attribute 8', value: '' },
  { key: 'ATTRIB_9', title: 'Attribute 9', value: '' },
  { key: 'ATTRIB_10', title: 'Attribute 10', value: '' },
  { key: 'SOLE_PROP', title: 'Natural person', value: '' },
  { key: 'ANN_SALES1', title: 'Currency amount', value: '' },
  { key: 'TAXJURCODE', title: 'Tax jurisdiction', value: '' },
  { key: 'FY_VARIANT', title: 'Fiscal year variant', value: '' },
  { key: 'DLVSCHEDUSE', title: 'Usage Indicator', value: '' },
  {
    key: 'INSPBYCUST',
    title: 'Inspection carried out by customer',
    value: '',
  },
  {
    key: 'INSPAFTDEL',
    title: 'Inspection for a delivery note',
    value: '',
  },
  { key: 'REF_ACTGR', title: 'reference account', value: '' },
  { key: 'PLANT', title: 'plant', value: '' },
  {
    key: 'DME_IND',
    title: 'report key for data medium exchange',
    value: '',
  },
  { key: 'INSTR_KEY', title: 'Industrial Key', value: '' },
  { key: 'DATA_TRANS', title: 'Data Transfer', value: '' },
  { key: 'ASSIGN_HI', title: 'Assignment to Heirarchy', value: '' },
  { key: 'PMNT_BLOCK', title: 'Payment Block', value: '' },
  { key: 'LABCUSTGRP', title: 'Customer/plant group', value: '' },
  { key: 'NON_MILIT', title: 'Id for non military use', value: '' },
  { key: 'MILIT_USE', title: 'Id for military use', value: '' },
  {
    key: 'CUST_COND_GRP1',
    title: 'Customer Condition Group 1',
    value: '',
  },
  {
    key: 'CUST_COND_GRP2',
    title: 'Customer Condition Group 2',
    value: '',
  },
  {
    key: 'CUST_COND_GRP3',
    title: 'Customer Condition Group 3',
    value: '',
  },
  {
    key: 'CUST_COND_GRP4',
    title: 'Customer Condition Group 4',
    value: '',
  },
  {
    key: 'CUST_COND_GRP5',
    title: 'Customer Condition Group 5',
    value: '',
  },
  { key: 'ALTPAYERAC', title: 'Alternative payer', value: '' },
  { key: 'TAX_TYPE', title: 'Tax Type', value: '' },
  { key: 'TAX_NO_TY', title: 'Tax No Type', value: '' },
  { key: 'TAX_NO_3', title: 'Tax No 3', value: '' },
  { key: 'TAX_NO_4', title: 'Tax No 4', value: '' },
  { key: 'NO_ICMS', title: 'is ICMS exempt', value: '' },
  { key: 'NO_IPI', title: 'is IPI exempt', value: '' },
  { key: 'SUBT_GRP', title: 'customer sub group', value: '' },
  { key: 'CFOP_CAT', title: 'CFOP category', value: '' },
  { key: 'TAXLAWICMS', title: 'Tax law ICMS', value: '' },
  { key: 'TAXLAWIPI', title: 'Tax law IPI', value: '' },
  { key: 'BCW', title: 'Bio Chemical warfare', value: '' },
  { key: 'NUCL_NONP', title: 'Nuclear non proliferation', value: '' },
  { key: 'NATL_SEC', title: 'National security', value: '' },
  { key: 'MISS_TECH', title: 'Missle Technology', value: '' },
  { key: 'SALES_BLKG', title: 'Sales Block', value: '' },
  { key: 'URL', title: 'Uniform Resource Locator', value: '' },
  { key: 'REP_NAME', title: 'Name of Representative', value: '' },
  { key: 'BUS_TYPE', title: 'Business Type', value: '' },
  { key: 'IND_TYPE', title: 'Industry Type', value: '' },
  { key: 'CONF_ST', title: 'Change of Authorization', value: '' },
  { key: 'CONF_DATE', title: 'Confirmed date', value: '' },
  { key: 'CONF_TIME', title: 'Confirmed time', value: '' },
  { key: 'NO_DELETE', title: 'central deletion block', value: '' },
  { key: 'CONSUMER', title: 'consumer', value: '' },
  { key: 'TAX_NO_5', title: 'Tax Number 5', value: '' },
  { key: 'PURP_CMPL_FLAG', title: 'Business Purpose Flag', value: '' },
];
export var VendorProfileHeaders: any = [
  {
    key: 'NAME',
    title: 'Name',
    value: '',
  },
  {
    key: 'VENDOR',
    title: 'Vendor',
    value: '',
  },
  {
    key: 'CITY',
    title: 'City',
    value: '',
  },
  {
    key: 'COMP_CODE',
    title: 'Company Code',
    value: '',
  },
  {
    key: 'NAME_2',
    title: 'Name 2',
    value: '',
  },
  {
    key: 'NAME_3',
    title: 'Name 3',
    value: '',
  },
  {
    key: 'NAME_4',
    title: 'Name 4',
    value: '',
  },
  {
    key: 'DISTRICT',
    title: 'District',
    value: '',
  },
  {
    key: 'PO_BOX',
    title: 'PO Box',
    value: '',
  },
  {
    key: 'POBX_PCD',
    title: 'P.O. Box Postal Code',
    value: '',
  },
  {
    key: 'POSTL_CODE',
    title: 'Postal Code',
    value: '',
  },
  {
    key: 'REGION',
    title: 'Region',
    value: '',
  },
  {
    key: 'STREET',
    title: 'Street',
    value: '',
  },
  {
    key: 'COUNTRY',
    title: 'Country',
    value: '',
  },
  {
    key: 'COUNTRYISO',
    title: 'Country ISO code',
    value: '',
  },
  {
    key: 'POBX_CTY',
    title: 'PO Box city',
    value: '',
  },
  {
    key: 'PAYMENT_METHODS',
    title: 'Payment Methods',
    value: '',
  },
  {
    key: 'PMNTTRMS',
    title: 'Payment Key',
    value: '',
  },
  {
    key: 'STREET',
    title: 'Street',
    value: '',
  },
  {
    key: 'REGION',
    title: 'Region',
    value: '',
  },
  {
    key: 'TELEPHONE',
    title: 'Telephone',
    value: '',
  },
  {
    key: 'CLERK',
    title: 'Accounting Clerk',
    value: '',
  },
  {
    key: 'HD_OFFICE',
    title: 'Head office',
    value: '',
  },
  {
    key: 'CUVD_CLEAR',
    title: 'Indicator: Clearing between customer and vendor?',
    value: '',
  },
  {
    key: 'ACT_AT_VEN',
    title: 'Our account number with the vendor',
    value: '',
  },
  {
    key: 'VEND_USER',
    title: 'Clerk at vendor',
    value: '',
  },
  {
    key: 'INTERNET',
    title: 'Internet address',
    value: '',
  },
  {
    key: 'FAX',
    title: 'fax number',
    value: '',
  },
  {
    key: 'BANK_CTRY',
    title: 'Bank country key',
    value: '',
  },
  {
    key: 'BANK_KEY',
    title: 'Bank Keys',
    value: '',
  },
  {
    key: 'BANK_ACCT',
    title: 'Bank account number',
    value: '',
  },
  {
    key: 'CTRL_KEY',
    title: 'Bank Control Key',
    value: '',
  },
  {
    key: 'IBAN',
    title: 'IBAN',
    value: '',
  },
  {
    key: 'VALID_FROM',
    title: 'Validity start of IBAN',
    value: '',
  },

  {
    key: 'LANGU',
    title: 'Language Key',
    value: '',
  },
  {
    key: 'LANGU_ISO',
    title: '2-Character SAP Language Code',
    value: '',
  },
  {
    key: 'TELEPHONE2',
    title: 'Second telephone number',
    value: '',
  },
];
export var EmployeeProfileHeader: any = [
  {
    key: 'ENAME',
    title: 'Name',
    value: '',
  },
  {
    key: 'PLANS_TXT',
    title: 'Position',
    value: '',
  },
  {
    key: 'KOKRS',
    title: 'Controlling Area',
    value: '',
  },
  {
    key: 'PERNR',
    title: 'Personnel Number',
    value: '',
  },
  {
    key: 'GBDAT',
    title: 'Date of Birth',
    value: '',
  },
  {
    key: 'ORT01',
    title: 'City',
    value: '',
  },
  {
    key: 'TELNR',
    title: 'Telephone Number',
    value: '',
  },
  {
    key: 'VORNA',
    title: 'First Name',
    value: '',
  },
  {
    key: 'NACHN',
    title: 'Last Name',
    value: '',
  },
  {
    key: 'GESCH',
    title: 'Gender',
    value: '',
  },  
  {
    key: 'NATIO',
    title: 'Nationality',
    value: '',
  },
  {
    key: 'KONFE',
    title: 'Religious Denomination Key',
    value: '',
  },
  {
    key: 'FAMST',
    title: 'Marital Status',
    value: '',
  },
  {
    key: 'PSTLZ',
    title: 'Postal code',
    value: '',
  },
  {
    key: 'STRAS',
    title: 'Street and House Number',
    value: '',
  },
  {
    key: 'LAND',
    title: 'Country Key',
    value: '',
  },
  {
    key: 'USRTY',
    title: 'Communication Type',
    value: '',
  },
  {
    key: 'SYSID',
    title: 'Communication Identification/Number',
    value: '',
  },
  {
    key: 'OTYPE',
    title: 'Object Type',
    value: '',
  },
  {
    key: 'STELL_TXT',
    title: 'STELL Object Name',
    value: '',
  },
  {
    key: 'ORGEH_TXT',
    title: 'Department',
    value: '',
  },
  {
    key: 'ORGEH',
    title: 'Organizational Unit',
    value: '',
  },
  {
    key: 'PLANS',
    title: 'Object ID',
    value: '',
  },
  {
    key: 'BEGDA',
    title: 'Start Date',
    value: '',
  },
  {
    key: 'ENDDA',
    title: 'End Date',
    value: '',
  },
  {
    key: 'STATUS',
    title: 'Employment Status',
    value: '',
  },
  {
    key: 'BUKRS',
    title: 'Company Code',
    value: '',
  },
  {
    key: 'WERKS',
    title: 'Personnel Area',
    value: '',
  },
  {
    key: 'PERSG',
    title: 'Employee Group',
    value: '',
  },
  {
    key: 'PERSK',
    title: 'Employee Subgroup',
    value: '',
  },
  {
    key: 'KOSTL',
    title: 'Cost Center',
    value: '',
  },
  {
    key: 'STELL',
    title: 'STELL Object ID',
    value: '',
  },

  {
    key: 'ANRED',
    title: 'Form-of-Address Key',
    value: '',
  },
];
