const vendorRequestForQuotationTableHead={
  "MANDT": "Client",
  "EBELN": "Purchasing Docu No",
  "BUKRS": "Company Code",
  "BSTYP": "pruchasing Document",
  "BSART": "Purchasing Document Type",
  "BSAKZ": "Purchase Document Control Type",
  "LOEKZ": "Purchase Document Deletion Indicator",
  "STATU": "Purchase Document Status",
  "AEDAT": "Date on Which the record was Created",
  "ERNAM": "Created User Name",
  "PINCR": "Item Number Interval",
  "LPONR": "Last Item Interval",
  "LIFNR": "Vendor Account Number",
  "SPRAS": "Language Key",
  "ZTERM": "Payment Key Terms",
  "ZBD1T": "Cash Discount Days 1",
  "ZBD2T": "Cash Discount Days 2",
  "ZBD3T": "Cash Discount Days 3",
  "ZBD1P": "Cash Discount percentage 1",
  "ZBD2P": "Cash Discount percentage 2",
  "EKORG": "Purchasing Organisation",
  "EKGRP": "Purchasing Group",
  "WAERS": "Currency Key",
  "WKURS": "Exchange Rate",
  "KUFIX": "Exchange Rate Fix Indicator",
  "BEDAT": "Purchasing Document Date",
  "KDATB": "Start Validity Period",
  "KDATE": "End Validity Period",
  "BWBDT": "Application Closing Date",
  "ANGDT": "Deadline For Submission",
  "BNDDT": "Binding Period for Quotation",
  "GWLDT": "Warranty Date",
  "AUSNR": "Bid Invitation Number",
  "ANGNR": "Quotation Number",
  "IHRAN": "Quotation Submission Date",
  "IHREZ": "Your Reference",
  "VERKF": "Responsible Sales Person",
  "TELF1": "Vendor Telephone Number",
  "LLIEF": "Suppling Vendor",
  "KUNNR": "Customer No",
  "KONNR": "Principal purchase Agreement number",
  "ABGRU": "Field Not used",
  "AUTLF": "Complete Delivery Stipulated for Each Purchase Order",
  "WEAKT": "Indicator: Goods Receipt Message",
  "RESWK": "Supplying (issuing) plant in case of stock transport order",
  "LBLIF": "Field not used",
  "INCO1": "Incoterms (Part 1)",
  "INCO2": "Incoterms (Part 2)",
  "KTWRT": "Target Value for Header Area per Distribution",
  "SUBMI": "Collective Number",
  "KNUMV": "Number of the document condition",
  "KALSM": "Procedure",
  "STAFO": "Statistics Update",
  "LIFRE": "Differenct Invoicing Party",
  "EXNUM": "No of Foreign Trade data in MM and SD Documents",
  "UNSEZ": "Our Reference",
  "LOGSY": "Logical System",
  "UPINC": "Item No Interval",
  "STAKO": "Document wiht time-dependent conditions",
  "FRGGR": "Release group",
  "FRGSX": "release Strategy",
  "FRGKE": "Release Indicator",
  "FRGZU": "Release State",
  "FRGRL": "Release Not yet Completely Effected",
  "LANDS": "Country for Tax Return",
  "LPHIS": "Indicator for scheduling agreement release documentation",
  "ADRNR": "Address No",
  "STCEG_L": "Countery of Sales Tax ID",
  "STCEG": "VAT Registration No",
  "ABSGR": "Reason for Cancellation",
  "ADDNR": "Document number for additional",
  "KORNR": "Correction of miscellaneous provisions",
  "MEMORY": "Purchase order not yet complete",
  "PROCSTAT": "Purchasing document processing state",
  "RLWRT": "Total value at time of release",
  "REVNO": "Version number in Purchasing",
  "SCMPROC": "SCM Process That Created the Purchase Order",
  "REASON_CODE": "Goods Receipt Reason Code",
  "MEMORYTYPE": "Category of Incompleteness",
  "RETTP": "Retention Indicator",
  "RETPC": "Retention in Percent",
  "DPTYP": "Down Payment Indicator",
  "DPPCT": "Down Payment Percentage",
  "DPAMT": "Down Payment Amount in Document Currency",
  "DPDAT": "Due Date for Down Payment",
  "MSR_ID": "Process Identification Number",
  "HIERARCHY_EXISTS": "Part of a Contract Hierarchy",
  "THRESHOLD_EXISTS": "Threshold Value for Exchange Rates Exists",
  "LEGAL_CONTRACT": "Legal Contract Number",
  "DESCRIPTION": "Contract Name",
  "RELEASE_DATE": "Release Date of Contract",
  "VSART": "Shipping type",
  "HANDOVERLOC": "Location for a physical handover of goods",
  "SHIPCOND": "Shipping conditions",
  "INCOV": "Incoterms Version",
  "INCO2_L": "Incoterms Location 1",
  "INCO3_L": "Incoterms Location 2",
  "FORCE_ID": "Incoterms key for Force Element",
  "FORCE_CNT": "Internal Counter",
  "RELOC_ID": "Relocation Step ID",
  "RELOC_SEQ_ID": "Relocation Step ID",
  "SOURCE_LOGSYS": "Logical System",
  "FSH_TRANSACTION": "Transaction No",
  "FSH_ITEM_GROUP": "Item Group",
  "FSH_VAS_LAST_ITEM": "Logical system",
  "FSH_OS_STG_CHANGE": "Order Scheduling Strategy",
  "VZSKZ": "Interest calculation Indicator",
  "FSH_SNST_STATUS": "Snapshort Status",
  "POHF_TYPE": "Purchase order processing Seasonal",
  "EQ_EINDT": "Delivery Date Header",
  "EQ_WERKS": "Plant Header",
  "FIXPO": "Firm Deal Indicator",
  "EKGRP_ALLOW": "Take Account of purchase Group",
  "WERKS_ALLOW": "Take Accounts of plants",
  "CONTRACT_ALLOW": "Take Account of Contracts",
  "PSTYP_ALLOW": "Take Account of Item Category",
  "FIXPO_ALLOW": "Take Account of Fixed-Date purchase Indicator",
  "KEY_ID_ALLOW": "Consider Budget",
  "AUREL_ALLOW": "Take Account of Alloc. Table Relevance",
  "DELPER_ALLOW": "Take Account of Dlvy Period",
  "EINDT_ALLOW": "Take Account of Delivery Date",
  "LTSNR_ALLOW": "Include Vendor Subrange",
  "OTB_LEVEL": "OTB Check Level",
  "OTB_COND_TYPE": "OTB Condition Type",
  "KEY_ID": "OTB-Relevant Data",
  "OTB_VALUE": "Unique Number of Budget",
  "OTB_CURR": "Required Budget",
  "OTB_RES_VALUE": "OTB Currency",
  "OTB_SPEC_VALUE": "OTB Currency",
  "SPR_RSN_PROFILE": "Reserved Budget for OTB-Relevant Purchasing Document",
  "BUDG_TYPE": "Budget Type",
  "OTB_STATUS": "OTB Check Status",
  "OTB_REASON": "Reason Indicator for OTB Check Status",
  "CHECK_TYPE": "Type of OTB Check",
  "CON_OTB_REQ": "OTB-Relevant Contract",
  "CON_PREBOOK_LEV": "OTB Indicator Level for Contracts",
  "CON_DISTR_LEV": "Distribution Using Target Value or Item Data",
  "CURR_DATE": "Current Date"
}
export default vendorRequestForQuotationTableHead;