const inquiryDataTableHead={
  "MANDT":"Client",
  "VBELN":"Sales Document",
  "ERDAT":"Date on which the record was created",
  "ERZET":"Entry time",
  "ERNAM":"Name of Person who Created the Object",
  "ANGDT":"Quotation/Inquiry is valid from",
  "BNDDT":"Date until which bid/quotation is binding",
  "AUDAT":"Document Date",
  "VBTYP":"SD document category",
  "TRVOG":"Transaction group",
  "AUART":"Sales Document Type",
  "AUGRU":"Order reason ",
  "GWLDT":"Guarantee date",
  "SUBMI":"Collective number (SD)",
  "LIFSK":"Delivery block (document header)",
  "FAKSK":"Billing block in SD document",
  "NETWR":"Net Value of the Sales Order",
  "WAERK":"SD document currency",
  "VKORG":"Sales Organization",
  "VTWEG":"Distribution Channel",
  "SPART":"Division",
  "VKGRP":"Sales group",
  "VKBUR":"Sales office",
  "GSBER":"Business Area",
  "GSKST":"Business area from cost center",
  "GUEBG":"Valid-from date",
  "GUEEN":"Valid-to date",
  "KNUMV":"Number of the document condition",
  "VDATU":"Requested delivery date",
  "VPRGR":"Proposed date type",
  "AUTLF":"Complete delivery",
  "VBKLA":"Original system with release and transaction control",
  "VBKLT":"SD document indicator",
  "KALSM":"Pricing Procedure",
  "VSBED":"Shipping conditions",
  "FKARA":"Proposed billing type",
  "AWAHR":"Sales probability",
  "KTEXT":"Search term for product proposal",
  "BSTNK":"Customer purchase order number",
  "BSARK":"Customer purchase order type",
  "BSTDK":"Customer purchase order date",
  "BSTZD":"Purchase order number supplement",
  "IHREZ":"Your Reference",
  "BNAME":"Name of orderer",
  "TELF1":"Telephone Number",
  "MAHZA":"Number of contacts",
  "MAHDT":"Last customer contact date",
  "KUNNR":"Sold-to party",
  "KOSTL":"Cost Center",
  "STAFO":"Update group for statistics update",
  "STWAE":"Statistics currency",
  "AEDAT":"Date of Last Change",
  "KVGR1":"Customer group 1",
  "KVGR2":"Customer group 2",
  "KVGR3":"Customer group 3",
  "KVGR4":"Customer group 4",
  "KVGR5":"Customer group 5",
  "KNUMA":"Agreement ",
  "KOKRS":"Controlling Area",
  "PS_PSP_PNR":"WBS Element",
  "KURST":"Exchange Rate Type",
  "KKBER":"Credit control area",
  "KNKLI":"Customer's account number",
  "GRUPP":"Customer Credit Group",
  "SBGRP":"Credit representative group",
  "CTLPC":"Credit management: Risk category",
  "CMWAE":"Currency key of credit control area",
  "CMFRE":"Release date of the document",
  "CMNUP":"Date of next credit check of document",
  "CMNGV":"Next date",
  "AMTBL":"Released credit value of the document",
  "HITYP_PR":"Hierarchy type for pricing",
  "ABRVW":"Usage Indicator",
  "ABDIS":"MRP for delivery schedule types",
  "VGBEL":"Document number",
  "OBJNR":"Object number at header level",
  "BUKRS_VF":"Company code to be billed",
  "TAXK1":"Tax classification 2 for customer",
  "TAXK2":"Tax classification 3 for customer",
  "TAXK3":"Tax classification 4 for customer",
  "TAXK4":"Tax classification 5 for customer",
  "TAXK5":"Tax classification 5 for customer",
  "TAXK6":"Tax classification 6 for customer",
  "TAXK7":"Tax classification 7 for customer",
  "TAXK8":"Tax classification 8 for customer",
  "TAXK9":"Tax classification 9 for customer",
  "XBLNR":"Reference Document Number",
  "ZUONR":"Assignment number",
  "VGTYP":"Document category",
  "KALSM_CH":"Search procedure for batch determination",
  "AGRZR":"Accrual period ",
  "AUFNR":"Order Number",
  "QMNUM":"Notification No",
  "VBELN_GRP":"Mster contract number",
  "SCHEME_GRP":"Referencing requirement: Procedure",
  "ABRUF_PART":"Check partner authorizations",
  "ABHOD":"Pick up date",
  "ABHOV":"Pick up time",
  "ABHOB":"Pick up time",
  "RPLNR":"Number of payment card plan type",
  "VZEIT":"Proposed schedule line time",
  "STCEG_L":"Tax Destination Country",
  "LANDTX":"Tax departure country",
  "XEGDR":"Indicator: Triangular deal ",
  "ENQUEUE_GRP":"Block master contr",
  "DAT_FZAU":"Cml delivery order qty date",
  "FMBDAT":"Material Availability Date",
  "VSNMR_V":"Sales document version number",
  "HANDLE":"International unique key for VBAK-VBELN",
  "PROLI":"Dangerous Goods Management Profile",
  "CONT_DG":"Indicator: Document contains dangerous goods",
  "CRM_GUID":"Character field",
  "UPD_TMSTMP":"UTC Time Stamp",
  "MSR_ID":"Process Identification Number",
  "TM_CTRL_KEY":"Control Key for Document Transfer",
  "HANDOVERLOC":"Location for a physical handover of goods",
  "_DATAAGING":"Data Filter Value for Data Aging",
  "PSM_BUDAT":"Posting Date in the Document",
  "FSH_KVGR6":"Customer Group 6",
  "FSH_KVGR7":"Customer Group 7",
  "FSH_KVGR8":"Customer Group 8",
  "FSH_KVGR9":"Customer Group 9",
  "FSH_KVGR10":"Customer Group 10",
  "FSH_REREG":"Release Rule",
  "FSH_CQ_CHECK":"Requirement Relevance for Contract",
  "FSH_VRSN_STATUS":"Snapshot Status",
  "FSH_TRANSACTION":"Transaction Number",
  "FSH_VAS_CG":"Value-Added Services Customer Group",
  "FSH_CANDATE":"Cancellation Date",
  "FSH_SS":"Order Scheduling Strategy -OSS",
  "FSH_OS_STG_CHANGE":"OSS specific fields change manually",
  "SWENR":"Business  Entity Number",
  "SMENR":"Number of Sales Unit",
  "PHASE":"Sales Phase",
  "MTLAUR":"Marker for Low Income Housing",
  "STAGE":"Construction Stage",
  "HB_CONT_REASON":"Contingency  data",
  "HB_EXPDATE":"Expiration date",
  "HB_RESDATE":"Resolution date",
  "MILL_APPL_ID":"Application ID Category for Configuration",
  "TAS":"Treasury Account Symbol",
  "BETC":"Business Event Type Code",
  "MOD_ALLOW":"Modification Allowed",
  "CANCEL_ALLOW":"Cancellation Allowed",
  "PAY_METHOD":"List of Respected Payment Methods",
  "BPN":"Business Partner Number",
  "REP_FREQ":"Reporting Frequency",
  "LOGSYSB":"Logical system",
  "KALCD":"Procedure for Campaign Determination",
  "MULTI":"Multiple Campaigns",
  "SPPAYM":"Payment Form for Special Payment Method",
  "WTYSC_CLM_HDR":"Claim header",
  
}

export default inquiryDataTableHead;