const vendorPurchaseOrderTableHead={
  "PO_NUMBER": "Purchase Document No",
  "PO_ITEM": "Purchase Order Item",
  "ADDRESS": "Address",
  "MATERIAL": "Material No",
  "PUR_MAT": "Materail No Pur",
  "INFO_REC": "Purchase Info Record",
  "ITEM_CAT": "Item Category",
  "ACCTASSCAT": "Account Assignment Category",
  "AGREEMENT": "Agreement",
  "AGMT_ITEM": "Agreement Item No",
  "STORE_LOC": "Storage No",
  "MAT_GRP": "Material Group",
  "SHORT_TEXT": "Description",
  "DISTRIB": "Distribution Indicator",
  "PART_INV": "Partial Invoice Indicator",
  "KANBAN_IND": "Kanban Indicator",
  "PLANT": "Plant",
  "ALLOC_TBL": "Allocation Table No",
  "AT_ITEM": "Allocation Table Item",
  "UNIT": "Order Unit",
  "NET_PRICE": "Net price",
  "PRICE_UNIT": "Price Unit",
  "CONV_NUM1": "Conversion numerator",
  "CONV_DEN1": "Conversion denominator",
  "ORDERPR_UN": "Order price unit",
  "PCKG_NO": "Package No",
  "PROMOTION": "Promotion",
  "ACKN_REQD": "Order Acknowledge Requirement",
  "TRACKINGNO": "Tracking No",
  "PLAN_DEL": "Plant Delivery Time",
  "RET_ITEM": "Returns Item",
  "AT_RELEV": "Allocation Table Relevant",
  "VEND_MAT": "Material Number Used By Vendor",
  "MANUF_PROF": "MFR part profile",
  "MANU_MAT": "Manufacture Part Number",
  "MFR_NO": "Manufacturer Number",
  "MFR_NO_EXT": "External Manufacturer cod ename",
  "PO_PRICE": "Adopt price Indicator",
  "SHIPPING": "Shipping Instructions",
  "ITEM_CAT_EXT": "Item Category in purchasing document",
  "PO_UNIT_ISO": "Order unit in ISO code",
  "ORDERPR_UN_ISO": "Purchase order ISO Unit",
  "PREQ_NAME": "Requisitioner Name",
  "DISP_QUAN": "Display quantity",
  "QUAL_INSP": "Stock Type",
  "NO_MORE_GR": "Delivery Completed Indicator",
  "DELETE_IND": "Deletion Indicator",
  "NO_ROUNDING": "Suppress Rounding purchase Indicator",
  "TAX_CODE": "Tax Code",
  "MATERIAL_EXTERNAL": "Material External Long No",
  "MATERIAL_GUID": "Material GUID No",
  "MATERIAL_VERSION": "Materail Version",
  "PUR_MAT_EXTERNAL": "PUR Material Exteranl Long No",
  "PUR_MAT_GUID": "PUR Material GUID No",
  "PUR_MAT_VERSION": "PUR Material Version",
  "VAL_TYPE": "Valuation Type",
  "PR_CLOSED": "Purchase requisition Closed",
  "ACKNOWL_NO": "Order Acknowledgement No",
  "REQ_SEGMENT": "Requirement Segment",
  "STK_SEGMENT": "Stock Segment",
  "MATERIAL_LONG": "Material Number Long",
  "PUR_MAT_LONG": "PUR Material Long"
}
export default vendorPurchaseOrderTableHead;