const vendorCreditDebitDemoTableHead={
  "COMP_CODE": "Company Code",
  "VENDOR": "Vendor Account No",
  "SP_GL_IND": "Special G/L Indicator",
  "CLEAR_DATE": "Clearing Date",
  "CLR_DOC_NO": "Clearing Doc No",
  "ALLOC_NMBR": "Assignment No",
  "FISC_YEAR": "Fiscal Year",
  "DOC_NO": "Accounting Doc No",
  "ITEM_NUM": "Item Number",
  "PSTNG_DATE": "Posting Date",
  "DOC_DATE": "Document Date",
  "ENTRY_DATE": "Entry Date",
  "CURRENCY": "Currency",
  "LOC_CURRCY": "Local Currency",
  "REF_DOC_NO": "Reference Doc No",
  "DOC_TYPE": "Document Type",
  "FIS_PERIOD": "Fiscal Period",
  "POST_KEY": "Posting Key",
  "DB_CR_IND": "Debit/Credit Indicator",
  "BUS_AREA": "Business Area",
  "TAX_CODE": "Tax Code",
  "LC_AMOUNT": "Amount in Local Currency",
  "AMT_DOCCUR": "Amount in Document Currency",
  "LC_TAX": "Tax Amount in Local Currency",
  "TX_DOC_CUR": "Tax Amount in Document Currency",
  "ITEM_TEXT": "Item Text",
  "BRANCH": "Branch Account No",
  "BLINE_DATE": "Baseline DAte",
  "PMNTTRMS": "Terms of Payment Key",
  "DSCT_DAYS1": "Cash Discount Days 1",
  "DSCT_DAYS2": "Cash Discount Days 2",
  "NETTERMS": "Payment key Terms",
  "DSCT_PCT1": "Cash Discount Percentage 1",
  "DSCT_PCT2": "Cash Discount Percentage 2",
  "DISC_BASE": "Amount Eligible for cash Discount",
  "DSC_AMT_LC": "Cash Discount Amount in Local Currency",
  "DSC_AMT_DC": "Payment Method",
  "PYMT_METH": "Payment Block key",
  "PMNT_BLOCK": "Fixed Payment Terms",
  "FIXEDTERMS": "Doc no of the  invoice to which the transaction belongs",
  "INV_REF": "Invoice Reference Doc no",
  "INV_YEAR": "Invoice Reference Doc no",
  "INV_ITEM": "Invoice Line Item",
  "DUNN_BLOCK": "Dunning LEvel",
  "DUNN_KEY": "Dunning key",
  "LAST_DUNN": "Last Dunning Notice",
  "DUNN_LEVEL": "Dunning Level",
  "DUNN_AREA": "Dunning Area",
  "W_TAX_CODE": "Withholding Tax Code",
  "W_TAX_BASE": "Withholding Tax Base Amount",
  "WI_TAX_AMT": "Withholding Tax Amount",
  "DOC_STATUS": "Document Status",
  "NXT_DOCTYP": "Follow on Document Type",
  "VAT_REG_NO": "VAT Register No",
  "EXEMPT_NO": "Tax Exemption No",
  "W_TAX_EXPT": "Withholding Tax Exempt Amount",
  "REASON_CDE": "Reason code for payments",
  "PMTMTHSUPL": "Payment method Supplement",
  "REF_KEY_1": "Business Partner Reference Key",
  "REF_KEY_2": "Business Partner Reference Key 2",
  "T_CURRENCY": "Update Currency for General Ledger",
  "AMOUNT": "Amount",
  "NET_AMOUNT": "Net Payment Amount",
  "NAME": "Name",
  "NAME_2": "Name 2",
  "NAME_3": "Name 3",
  "NAME_4": "Name 4",
  "POSTL_CODE": "Postal Code",
  "CITY": "City",
  "COUNTRY": "Country",
  "STREET": "Street",
  "PO_BOX": "PO BOx",
  "POBX_PCD": "PO Box Postal Code",
  "POBK_CURAC": "Account No of Bank Account",
  "BANK_ACCT": "Bank Account No",
  "BANK_KEY": "Bank keys",
  "BANK_CTRY": "Bank Country Key",
  "TAX_NO_1": "Tax No 1",
  "TAX_NO_2": "Tax No 2",
  "TAX": "Tax",
  "EQUAL_TAX": "Equalization Tax",
  "REGION": "Region",
  "CTRL_KEY": "Control Key",
  "INSTR_KEY": "Instruction Key",
  "PAYEE_CODE": "Payee code",
  "LANGU": "Language",
  "BILL_LIFE": "Bill Life",
  "BE_TAXCODE": "Bill Tax Code",
  "BILLTAX_LC": "Exchange Bill Tax in Local Currency",
  "BILLTAX_FC": "Exchange Bill Tax in Foreign Currency",
  "LC_COL_CHG": "Exchange Bill Collection Charge",
  "COLL_CHARG": "Exchange Bill Collection in Document No",
  "CHGS_TX_CD": "Tax Code for bill of exchange charges",
  "ISSUE_DATE": "Issue Date",
  "USAGEDATE": "Usage Date",
  "BILL_USAGE": "Bill Usage",
  "DOMICILE": "Bank Address",
  "DRAWER": "Exchange Name Drawer",
  "CTRBNK_LOC": "State Central Bank Location",
  "DRAW_CITY1": "Exchange Bill Drawer City",
  "DRAWEE": "Exchange Bill Drawee",
  "DRAW_CITY2": "Excange Bill Drawer City 2",
  "DISCT_DAYS": "Discount Days",
  "DISCT_RATE": "Discount Rate",
  "ACCEPTED": "Accepted Bill Exchange",
  "BILLSTATUS": "Bill Status",
  "PRTEST_IND": "Exchange Protest Indicatpr",
  "BE_DEMAND": "Bill on Demand",
  "OBJ_TYPE": "Reference Procedure",
  "REF_DOC": "Refernce Document No",
  "REF_ORG_UN": "Reference Organisation Unit",
  "REVERSAL_DOC": "Reversal Document No",
  "SP_GL_TYPE": "Special G/L Transaction Type",
  "NEG_POSTNG": "Negative Posting",
  "REF_DOC_NO_LONG": "Reference Doc No Long",
}
export default vendorCreditDebitDemoTableHead;