const customerListOfDeliveryTableHead={
  "MANDT": "Client",
  "VBELN": "Delivery",
  "POSNR": "Delivery Item",
  "PSTYV": "Delivery Item Category",
  "ERNAM": "Creator Name",
  "ERZET": "Entry Time",
  "ERDAT": "Entry Date",
  "MATNR": "Material Number",
  "MATWA": "Material Entered",
  "MATKL": "Material Group",
  "WERKS": "Plant",
  "LGORT": "Storage Location",
  "CHARG": "Batch Mo",
  "LICHN": "Vendor Batch No",
  "KDMAT": "Material Belonging to Customer",
  "PRODH": "Product Hierarchy",
  "LFIMG": "Actual Quantity Delivered",
  "MEINS": "Basic unit of Measure",
  "VRKME": "Sales Unit",
  "UMVKZ": "Numerator (factor) for conversion of sales quantity into SKU",
  "UMVKN": "Denominator (factor) for conversion of sales quantity into SKU",
  "NTGEW": "Net Weight",
  "BRGEW": "Gross Weight",
  "GEWEI": "Weight Unit",
  "VOLUM": "Volume",
  "VOLEH": "Volume Unit",
  "KZTLF": "Partial Delivery",
  "UEBTK": "OverDelivery Allowed Indicator",
  "UEBTO": "OverDelivery Tolerance Limit",
  "UNTTO": "UnderDelivery Tolerance Limit",
  "CHSPL": "Batch Split Allowed",
  "FAKSP": "Block",
  "MBDAT": "Material Availability Date",
  "LGMNG": "Actual Quantity Delivered in Stock Keeper",
  "ARKTX": "Short Text for Sales Order iterm",
  "LGPBE": "Storage Bin",
  "VBELV": "Orginating Document",
  "POSNV": "Orginating Item",
  "VBTYV": "SD Document Category",
  "VGSYS": "Logical System in preceing Document",
  "VGBEL": "Reference Document No",
  "VGPOS": "Reference Item No",
  "UPFLU": "Update indicator for delivery document flow",
  "UEPOS": "Higher Level Item in Material Structure",
  "FKREL": "Relevant for billing",
  "LADGR": "Loading Group",
  "TRAGR": "Transportation Group",
  "KOMKZ": "Indicator for picking control",
  "LGNUM": "Warehouse No",
  "LISPL": "Split to warehouse number required",
  "LGTYP": "Storage Type",
  "LGPLA": "Storage Bin",
  "BWTEX": "Separate Valuation",
  "BWART": "Movement Type",
  "BWLVS": "Movement Type for warehouse",
  "KZDLG": "Indicator",
  "BDART": "Requirement type",
  "PLART": "Planning type",
  "MTART": "Material Type",
  "XCHPF": "Batch Management requirement Indicator",
  "XCHAR": "Batch management indicator (internal)",
  "VGREF": "Preceding document has resulted from reference",
  "POSAR": "Item type",
  "BWTAR": "Valuation Type",
  "SUMBD": "Summing up of Requirements",
  "MTVFP": "Checking Group for Availability Check",
  "EANNR": "European Article Number",
  "GSBER": "Business Area",
  "VKBUR": "Sales Office",
  "VKGRP": "Sales Group",
  "VTWEG": "Distribution Channel",
  "SPART": "Division",
  "GRKOR": "Delivery Group",
  "FMENG": "Quantity Fixed",
  "ANTLF": "Maximum Number of Partial Deliveries Allowed Per Item",
  "VBEAF": "Fixed shipping processing time in days (= setup time)",
  "VBEAV": "Variable shipping processing time in days",
  "STAFO": "Update group for statistics update",
  "WAVWR": "Cost in document Currency",
  "KZWI1": "Subtotal 1 from pricing procedure for condition",
  "KZWI2": "Subtotal 2 from pricing procedure for condition",
  "KZWI3": "Subtotal 3 from pricing procedure for condition",
  "KZWI4": "Subtotal 4 from pricing procedure for condition",
  "KZWI5": "Subtotal 5 from pricing procedure for condition",
  "KZWI6": "Subtotal 6 from pricing procedure for condition",
  "SOBKZ": "Special Stock Indicator",
  "AEDAT": "Date of Last change",
  "EAN11": "Internation Article No",
  "KVGR1": "Customer group 1",
  "KVGR2": "Customer group 2",
  "KVGR3": "Customer group 3",
  "KVGR4": "Customer group 4",
  "KVGR5": "Customer group 5",
  "MVGR1": "Material group 1",
  "MVGR2": "Material group 2",
  "MVGR3": "Material group 3",
  "MVGR4": "Material group 4",
  "MVGR5": "Material group 5",
  "VPZUO": "Allocation Indicator",
  "VGTYP": "SD Document Category",
  "RFVGTYP": "Type of Preceding in Central System",
  "KOSTL": "Cost Center",
  "KOKRS": "Controlling Area",
  "PAOBJNR": "Profitability Segment Number (CO-PA)",
  "PRCTR": "Profit Center",
  "PS_PSP_PNR": "Work Breakdown Structure Element (WBS Element)",
  "AUFNR": "Order Number",
  "POSNR_PP": "Order Item number",
  "KDAUF": "Sales Order No",
  "KDPOS": "Item Number in Sales Order",
  "VPMAT": "Planning Material",
  "VPWRK": "Plannning Plant",
  "PRBME": "Base Unit of measure for Product Group",
  "UMREF": "Conversion factor: quantities",
  "KNTTP": "Account Assignment Category",
  "KZVBR": "Consumption posting",
  "FIPOS": "Commitment posting",
  "FISTL": "Commitment Item",
  "GEBER": "Funds Center",
  "PCKPF": "Fund",
  "BEDAR_LF": "Packing control",
  "CMPNT": "Requirement Class",
  "KCMENG": "D: Item with active credit function / relevant for credit",
  "KCBRGEW": "Cumulative batch quantity of all split items (in StckUnit)",
  "KCNTGEW": "Cumulative gross weight of all batch split items",
  "KCVOLUM": "Cumulative net weight of all batch split items",
  "UECHA": "Higher-Level Item of Batch Split Item",
  "CUOBJ": "Configuration",
  "CUOBJ_CH": "Internal object number of the batch classification",
  "ANZSN": "Number of serial numbers",
  "SERAIL": "Serial Number Profile",
  "KCGEWEI": "Weight Unit",
  "KCVOLEH": "Volume Unit",
  "SERNR": "BOM Explosion Number",
  "ABRLI": "Internal Delivery Schedule No",
  "ABART": "Rel. Type",
  "ABRVW": "Usage Indicator",
  "QPLOS": "Inspection Lot nubmer",
  "QTLOS": "Partial Lot Number",
  "NACHL": "Customer has not posted goods receipt",
  "MAGRV": "Material Group: Packaging Materials",
  "OBJKO": "Object number at header level",
  "OBJPO": "Object number at item level",
  "AESKD": "Customer Engineering Change Status",
  "SHKZG": "Returns Item",
  "PROSA": "Material Determination Id",
  "UEPVW": "Higher Level Item Usage",
  "EMPST": "Receiving point",
  "ABTNR": "Department No",
  "KOQUI": "Picking is Subject to confirmation",
  "STADAT": "Statistics Date",
  "AKTNR": "Promotion",
  "KNUMH_CH": "Number of condition record from batch determination",
  "PREFE": "Preference Indicator in export/import",
  "EXART": "Business Transaction Type for Foreign Trade",
  "CLINT": "Internal Class No",
  "CHMVS": "Batches:Exit to quanity proposal",
  "ABELN": "Allocation Table Number",
  "ABELP": "Item number of allocation table",
  "LFIMG_FLO": "Internal field/ Do not use ",
  "LGMNG_FLO": "Internal field/ Do not use ",
  "KCMENG_FLO": "Internal field/ Do not use ",
  "KZUMW": "Environmentally Relevant",
  "KMPMG": "Component Quantity",
  "AUREL": "Relevant to Allocation tables",
  "KPEIN": "Condition pricin unit",
  "KMEIN": "Condition unit",
  "NETPR": "Net price",
  "NETWR": "Net value",
  "KOWRR": "Statistical values",
  "KZBEW": "Movement Indicator",
  "MFRGR": "Material Freight group",
  "CHHPV": "Pack accumulated batches",
  "ABFOR": "Form of payment Guarantee",
  "ABGES": "Guaranted",
  "MBUHR": "Material Staging Time",
  "WKTNR": "Value Contract No",
  "WKTPS": "Value Contract Item",
  "J_1BCFOP": "CFOP Code and Extension",
  "J_1BTAXLW1": "Tax law: ICMS",
  "J_1BTAXLW2": "Tax law: IPI",
  "J_1BTXSDC": "SD Tax Code",
  "SITUA": "Situation Indicator",
  "RSNUM": "Number of reservation",
  "RSPOS": "Item Number of Reservation",
  "RSART": "Record Type",
  "KANNR": "Sequence Number",
  "KZFME": "ID: Leading unit of measure for completing a transaction",
  "PROFL": "Dangerous Goods Indicator Profile",
  "KCMENGVME": "Cumulative batch quantity of all split items in sales units",
  "KCMENGVMEF": "Cumulated batch split quantity in VRKME and float",
  "KZBWS": "Valuation of Special Stock",
  "PSPNR": "Project definition (internal)",
  "EPRIO": "Withdrawal Sequence Group for Stocks",
  "RULES": "Stock determination rule",
  "KZBEF": "Indicator Inventory Management active",
  "MPROF": "Mfr part profile",
  "EMATN": "Material number corresponding to manufacturer part number",
  "LGBZO": "Staging Area for Warehouse Complex",
  "HANDLE": "Worldwide unique key for LIPS-VBELN & LIPS_POSNR",
  "VERURPOS": "Distribution delivery: Original item",
  "LIFEXPOS": "External item number",
  "NOATP": "Indicator: deactivate availability check",
  "NOPCK": "Indicator: not relevant for picking",
  "RBLVS": "Reference movement type for WM from material movements",
  "BERID": "MRP AREA",
  "BESTQ": "Stock Category",
  "UMBSQ": "Stock Category 2",
  "UMMAT": "Receiving/Issue Material",
  "UMWRK": "Receiving plant/issuing plant",
  "UMLGO": "Receiving/issuing storage location",
  "UMCHA": "Receiving/Issuing Batch",
  "UMBAR": "Valuation Type of Transfer Batch",
  "UMSOK": "Special stock indicator for physical stock transfer",
  "SONUM": "Special Stock Number",
  "USONU": "Special Stock Number 2",
  "AKKUR": "Exchange rate for letter-of-credit procg in foreign trade",
  "AKMNG": "Current Qty Field for Arithmetic Operations in Doc.Process.",
  "VKGRU": "Repair Processing: Classification of Items",
  "SHKZG_UM": "Indicator: UNMAT in main posting",
  "INSMK": "Stock Type",
  "KZECH": "Determination of batch entry in the production/process order",
  "FLGWM": "Indicator: Copy dest. storage data from preceding document",
  "BERKZ": "Material Staging Indicator for Production Supply",
  "HUPOS": "Indicator: Delivery item is a HU item",
  "NOWAB": "Indicator: Item Not Relevant for Goods Movements",
  "KONTO": "G/L Account Number",
  "KZEAR": "Final issue for this reservation",
  "HSDAT": "Date of Manufacture",
  "VFDAT": "Shelf Life Expiration or Best-Before Date",
  "LFGJA": "Fiscal Year of Current Period",
  "LFBNR": "Document No. of a Reference Document",
  "LFPOS": "Item of a Reference Document",
  "GRUND": "Reason for goods movment",
  "FOBWA": "Subsequent movement type",
  "DLVTP": "Delivery Category",
  "EXBWR": "Externally Entered Posting Amount in Local Currency",
  "BPMNG": "Quantity in Purchase Order Price Unit",
  "EXVKW": "Externally Entered Sales Value in Local Currency",
  "CMPRE_FLT": "Item credit price",
  "KZPOD": "POD indicator (relevance, verification, confirmation)",
  "LFDEZ": "Not relevant for distribution for WMS",
  "UMREV": "Conversion Factor of Delivery Quantity VRKME for MEINS",
  "PODREL": "POD Control (Proof of Delivery)",
  "KZUML": "Stock transfer/transfer posting",
  "FKBER": "Functional Area",
  "GRANT_NBR": "Grant",
  "KZWSO": "Units of measure usage",
  "GMCONTROL": "Goods Movement Control",
  "POSTING_CHANGE": "Goods Movement Control: HU",
  "UM_PS_PSP_PNR": "Receiving/Issuing (WBS Element)",
  "PRE_VL_ETENS": "Sequential Number of Vendor Confirmation",
  "SPE_GEN_ELIKZ": "Delivery Completed Indicator",
  "SPE_SCRAP_IND": "Scrap Indicator for EWM Processing",
  "SPE_AUTH_NUMBER": "Return Material Authorization Numbe",
  "SPE_INSPOUT_GUID": "Inspections: Inspection outcome GUID set by EWM",
  "SPE_FOLLOW_UP": "Default Follow-Up Activity Code",
  "SPE_EXP_DATE_EXT": "End date of validity period of returns delivery",
  "SPE_EXP_DATE_INT": "End date of internal validity period of returns delivery",
  "SPE_AUTH_COMPLET": "RMA completion indicator",
  "ORMNG": "Original Quantity of Delivery Item",
  "SPE_ATP_TMSTMP": "ATP Time Stamp",
  "SPE_ORIG_SYS": "Original System Type",
  "SPE_LIEFFZ": "Cumulative Qty for SchedAgr - Vendor's Point of View",
  "SPE_IMWRK": "Inbound Delivery item has Status 'In Plant'",
  "SPE_LIFEXPOS2": "External item identifier",
  "SPE_EXCEPT_CODE": "Exception Code Warehouse for Quantity Difference",
  "SPE_KEEP_QTY": "Retention Quantity for Scrap. Process in EWM",
  "SPE_ALTERNATE": "Alternate Product Number",
  "SPE_MAT_SUBST": "Reason for material substitution",
  "SPE_STRUC": "Structure of Items That Are Delivered Together",
  "SPE_EXP_DATE_EXT_B": "Begin date of validity period of returns delivery",
  "STK_SEGMENT": "Stock Segment",
  "REQ_SEGMENT": "Requirement Segment",
  "MATNR_LONG": "Material No Long",
  "MATWA_LONG": "Material Entered",
  "VPMAT_LONG": "Planning Material",
  "EMATN_LONG": "Material number corresponding to MPN (technically required)",
  "UMMAT_LONG": "Receiving/Issuing Material",
  "VBTYV_LONG": "Field is not supported – needed for technical reasons only",
  "VGTYP_LONG": "Field is not supported – needed for technical reasons only",
  "RFVGTYP_LONG": "Field is not supported – needed for technical reasons only"
};
export default customerListOfDeliveryTableHead;